//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/internal/requests/OrderingRequest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitInternalRequestsOrderingRequest")
#ifdef RESTRICT_OrgJunitInternalRequestsOrderingRequest
#define INCLUDE_ALL_OrgJunitInternalRequestsOrderingRequest 0
#else
#define INCLUDE_ALL_OrgJunitInternalRequestsOrderingRequest 1
#endif
#undef RESTRICT_OrgJunitInternalRequestsOrderingRequest

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitInternalRequestsOrderingRequest_) && (INCLUDE_ALL_OrgJunitInternalRequestsOrderingRequest || defined(INCLUDE_OrgJunitInternalRequestsOrderingRequest))
#define OrgJunitInternalRequestsOrderingRequest_

#define RESTRICT_OrgJunitInternalRequestsMemoizingRequest 1
#define INCLUDE_OrgJunitInternalRequestsMemoizingRequest 1
#include "org/junit/internal/requests/MemoizingRequest.h"

@class OrgJunitRunnerManipulationOrdering;
@class OrgJunitRunnerRequest;
@class OrgJunitRunnerRunner;

/*!
 @since 4.13
 */
@interface OrgJunitInternalRequestsOrderingRequest : OrgJunitInternalRequestsMemoizingRequest

#pragma mark Public

- (instancetype __nonnull)initWithOrgJunitRunnerRequest:(OrgJunitRunnerRequest *)request
                 withOrgJunitRunnerManipulationOrdering:(OrgJunitRunnerManipulationOrdering *)ordering;

#pragma mark Protected

- (OrgJunitRunnerRunner *)createRunner;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initPackagePrivate NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitInternalRequestsOrderingRequest)

FOUNDATION_EXPORT void OrgJunitInternalRequestsOrderingRequest_initWithOrgJunitRunnerRequest_withOrgJunitRunnerManipulationOrdering_(OrgJunitInternalRequestsOrderingRequest *self, OrgJunitRunnerRequest *request, OrgJunitRunnerManipulationOrdering *ordering);

FOUNDATION_EXPORT OrgJunitInternalRequestsOrderingRequest *new_OrgJunitInternalRequestsOrderingRequest_initWithOrgJunitRunnerRequest_withOrgJunitRunnerManipulationOrdering_(OrgJunitRunnerRequest *request, OrgJunitRunnerManipulationOrdering *ordering) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitInternalRequestsOrderingRequest *create_OrgJunitInternalRequestsOrderingRequest_initWithOrgJunitRunnerRequest_withOrgJunitRunnerManipulationOrdering_(OrgJunitRunnerRequest *request, OrgJunitRunnerManipulationOrdering *ordering);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalRequestsOrderingRequest)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitInternalRequestsOrderingRequest")
