//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/experimental/theories/ParametersSuppliedBy.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitExperimentalTheoriesParametersSuppliedBy")
#ifdef RESTRICT_OrgJunitExperimentalTheoriesParametersSuppliedBy
#define INCLUDE_ALL_OrgJunitExperimentalTheoriesParametersSuppliedBy 0
#else
#define INCLUDE_ALL_OrgJunitExperimentalTheoriesParametersSuppliedBy 1
#endif
#undef RESTRICT_OrgJunitExperimentalTheoriesParametersSuppliedBy

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitExperimentalTheoriesParametersSuppliedBy_) && (INCLUDE_ALL_OrgJunitExperimentalTheoriesParametersSuppliedBy || defined(INCLUDE_OrgJunitExperimentalTheoriesParametersSuppliedBy))
#define OrgJunitExperimentalTheoriesParametersSuppliedBy_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

/*!
 @brief Annotating a <code>Theory</code> method
  parameter with &#064;ParametersSuppliedBy causes it to be supplied with
  values from the named 
 <code>ParameterSupplier</code>
  when run as a theory by the <code>Theories</code>
  runner.
 In addition, annotations themselves can be annotated with 
 &#064;ParametersSuppliedBy, and then used similarly. ParameterSuppliedBy
  annotations on parameters are detected by searching up this hierarchy such
  that these act as syntactic sugar, making:  
 @code

   &#064;ParametersSuppliedBy(Supplier.class)
  public &#064;interface SpecialParameter { }  
  &#064;Theory
  public void theoryMethod(&#064;SpecialParameter String param) {
    ...
  } 
  
@endcode
  
  equivalent to:  
 @code

   &#064;Theory
  public void theoryMethod(&#064;ParametersSuppliedBy(Supplier.class) String param) {
    ...
  } 
  
@endcode
 */
@protocol OrgJunitExperimentalTheoriesParametersSuppliedBy < JavaLangAnnotationAnnotation >

@property (readonly) IOSClass *value;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface OrgJunitExperimentalTheoriesParametersSuppliedBy : NSObject < OrgJunitExperimentalTheoriesParametersSuppliedBy > {
 @public
  IOSClass *value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitExperimentalTheoriesParametersSuppliedBy)

FOUNDATION_EXPORT id<OrgJunitExperimentalTheoriesParametersSuppliedBy> create_OrgJunitExperimentalTheoriesParametersSuppliedBy(IOSClass *value);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitExperimentalTheoriesParametersSuppliedBy)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitExperimentalTheoriesParametersSuppliedBy")
