//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/build_result/java/com/google/common/collect/CollectSpliterators.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators")
#ifdef RESTRICT_ComGoogleCommonCollectCollectSpliterators
#define INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators 1
#endif
#undef RESTRICT_ComGoogleCommonCollectCollectSpliterators
#ifdef INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble
#define INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong
#define INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt
#define INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive
#define INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject
#define INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator 1
#endif

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonCollectCollectSpliterators_) && (INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators || defined(INCLUDE_ComGoogleCommonCollectCollectSpliterators))
#define ComGoogleCommonCollectCollectSpliterators_

@protocol JavaUtilComparator;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilFunctionIntFunction;
@protocol JavaUtilFunctionPredicate;
@protocol JavaUtilSpliterator;
@protocol JavaUtilSpliterator_OfDouble;
@protocol JavaUtilSpliterator_OfInt;
@protocol JavaUtilSpliterator_OfLong;

/*!
 @brief Spliterator utilities for <code>common.collect</code> internals.
 */
@interface ComGoogleCommonCollectCollectSpliterators : NSObject

#pragma mark Package-Private

/*!
 @brief Returns a <code>Spliterator</code> filtered by the specified predicate.
 */
+ (id<JavaUtilSpliterator>)filterWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)fromSpliterator
                           withJavaUtilFunctionPredicate:(id<JavaUtilFunctionPredicate> __nonnull)predicate;

/*!
 @brief Returns a <code>Spliterator</code> that iterates over the elements of the spliterators generated by
  applying <code>function</code> to the elements of <code>fromSpliterator</code>.
 */
+ (id<JavaUtilSpliterator>)flatMapWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)fromSpliterator
                             withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
                                                  withInt:(jint)topCharacteristics
                                                 withLong:(jlong)topSize;

/*!
 @brief Returns a <code>Spliterator.OfDouble</code> that iterates over the elements of the spliterators
  generated by applying <code>function</code> to the elements of <code>fromSpliterator</code>.
 (If <code>function</code>
  returns <code>null</code> for an input, it is replaced with an empty stream.)
 */
+ (id<JavaUtilSpliterator_OfDouble>)flatMapToDoubleWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)fromSpliterator
                                              withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
                                                                   withInt:(jint)topCharacteristics
                                                                  withLong:(jlong)topSize;

/*!
 @brief Returns a <code>Spliterator.OfInt</code> that iterates over the elements of the spliterators
  generated by applying <code>function</code> to the elements of <code>fromSpliterator</code>.
 (If <code>function</code>
  returns <code>null</code> for an input, it is replaced with an empty stream.)
 */
+ (id<JavaUtilSpliterator_OfInt>)flatMapToIntWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)fromSpliterator
                                        withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
                                                             withInt:(jint)topCharacteristics
                                                            withLong:(jlong)topSize;

/*!
 @brief Returns a <code>Spliterator.OfLong</code> that iterates over the elements of the spliterators
  generated by applying <code>function</code> to the elements of <code>fromSpliterator</code>.
 (If <code>function</code>
  returns <code>null</code> for an input, it is replaced with an empty stream.)
 */
+ (id<JavaUtilSpliterator_OfLong>)flatMapToLongWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)fromSpliterator
                                          withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
                                                               withInt:(jint)topCharacteristics
                                                              withLong:(jlong)topSize;

+ (id<JavaUtilSpliterator>)indexedWithInt:(jint)size
                                  withInt:(jint)extraCharacteristics
          withJavaUtilFunctionIntFunction:(id<JavaUtilFunctionIntFunction> __nonnull)function;

+ (id<JavaUtilSpliterator>)indexedWithInt:(jint)size
                                  withInt:(jint)extraCharacteristics
          withJavaUtilFunctionIntFunction:(id<JavaUtilFunctionIntFunction> __nonnull)function
                   withJavaUtilComparator:(id<JavaUtilComparator> __nonnull)comparator;

/*!
 @brief Returns a <code>Spliterator</code> over the elements of <code>fromSpliterator</code> mapped by <code>function</code>
 .
 */
+ (id<JavaUtilSpliterator>)mapWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)fromSpliterator
                         withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectCollectSpliterators)

FOUNDATION_EXPORT id<JavaUtilSpliterator> ComGoogleCommonCollectCollectSpliterators_indexedWithInt_withInt_withJavaUtilFunctionIntFunction_(jint size, jint extraCharacteristics, id<JavaUtilFunctionIntFunction> function);

FOUNDATION_EXPORT id<JavaUtilSpliterator> ComGoogleCommonCollectCollectSpliterators_indexedWithInt_withInt_withJavaUtilFunctionIntFunction_withJavaUtilComparator_(jint size, jint extraCharacteristics, id<JavaUtilFunctionIntFunction> function, id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT id<JavaUtilSpliterator> ComGoogleCommonCollectCollectSpliterators_mapWithJavaUtilSpliterator_withJavaUtilFunctionFunction_(id<JavaUtilSpliterator> fromSpliterator, id<JavaUtilFunctionFunction> function);

FOUNDATION_EXPORT id<JavaUtilSpliterator> ComGoogleCommonCollectCollectSpliterators_filterWithJavaUtilSpliterator_withJavaUtilFunctionPredicate_(id<JavaUtilSpliterator> fromSpliterator, id<JavaUtilFunctionPredicate> predicate);

FOUNDATION_EXPORT id<JavaUtilSpliterator> ComGoogleCommonCollectCollectSpliterators_flatMapWithJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator> fromSpliterator, id<JavaUtilFunctionFunction> function, jint topCharacteristics, jlong topSize);

FOUNDATION_EXPORT id<JavaUtilSpliterator_OfInt> ComGoogleCommonCollectCollectSpliterators_flatMapToIntWithJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator> fromSpliterator, id<JavaUtilFunctionFunction> function, jint topCharacteristics, jlong topSize);

FOUNDATION_EXPORT id<JavaUtilSpliterator_OfLong> ComGoogleCommonCollectCollectSpliterators_flatMapToLongWithJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator> fromSpliterator, id<JavaUtilFunctionFunction> function, jint topCharacteristics, jlong topSize);

FOUNDATION_EXPORT id<JavaUtilSpliterator_OfDouble> ComGoogleCommonCollectCollectSpliterators_flatMapToDoubleWithJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator> fromSpliterator, id<JavaUtilFunctionFunction> function, jint topCharacteristics, jlong topSize);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectCollectSpliterators)

#endif

#if !defined (ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_) && (INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators || defined(INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator))
#define ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_

#define RESTRICT_JavaUtilSpliterator 1
#define INCLUDE_JavaUtilSpliterator 1
#include "java/util/Spliterator.h"

@protocol ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory;
@protocol JavaUtilComparator;
@protocol JavaUtilFunctionConsumer;
@protocol JavaUtilFunctionFunction;

/*!
 @brief Implements the <code>Stream.flatMap</code> operation on spliterators.
 */
@interface ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator : NSObject < JavaUtilSpliterator > {
 @public
  WEAK_ id<JavaUtilSpliterator> prefix_;
  id<JavaUtilSpliterator> from_;
  id<JavaUtilFunctionFunction> function_;
  id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory> factory_;
  jint characteristics_;
  jlong estimatedSize_;
}

#pragma mark Public

- (jint)characteristics;

- (jlong)estimateSize;

- (void)forEachRemainingWithJavaUtilFunctionConsumer:(id<JavaUtilFunctionConsumer> __nonnull)action;

- (jboolean)tryAdvanceWithJavaUtilFunctionConsumer:(id<JavaUtilFunctionConsumer> __nonnull)action;

- (id<JavaUtilSpliterator>)trySplit;

#pragma mark Package-Private

- (instancetype __nonnull)initWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)prefix
                              withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)from
                         withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
withComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory:(id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory> __nonnull)factory
                                              withInt:(jint)characteristics
                                             withLong:(jlong)estimatedSize;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator, from_, id<JavaUtilSpliterator>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator, function_, id<JavaUtilFunctionFunction>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator, factory_, id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory>)

FOUNDATION_EXPORT void ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_initWithJavaUtilSpliterator_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory_withInt_withLong_(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator *self, id<JavaUtilSpliterator> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory> factory, jint characteristics, jlong estimatedSize);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator)

#endif

#if !defined (ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory_) && (INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators || defined(INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory))
#define ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory_

@protocol JavaUtilFunctionFunction;
@protocol JavaUtilSpliterator;

/*!
 @brief Factory for constructing <code>FlatMapSpliterator</code> instances.
 */
@protocol ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory < JavaObject >

- (id<JavaUtilSpliterator>)newFlatMapSpliteratorWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)prefix
                                                withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)fromSplit
                                           withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
                                                                withInt:(jint)splitCharacteristics
                                                               withLong:(jlong)estSplitSize OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory)

#endif

#if !defined (ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject_) && (INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators || defined(INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject))
#define ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject_

@protocol ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilSpliterator;

/*!
 @brief Implementation of <code>Stream.flatMap</code> with an object spliterator output type.
 <p>To avoid having this type, we could use <code>FlatMapSpliterator</code> directly. The main
  advantages to having the type are the ability to use its constructor reference below and the
  parallelism with the primitive version. In short, it makes its caller (<code>flatMap</code>)
  simpler.
 */
@interface ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject : ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator

#pragma mark Package-Private

- (instancetype __nonnull)initWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)prefix
                              withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)from
                         withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
                                              withInt:(jint)characteristics
                                             withLong:(jlong)estimatedSize;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)arg0
                              withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)arg1
                         withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)arg2
withComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory:(id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory> __nonnull)arg3
                                              withInt:(jint)arg4
                                             withLong:(jlong)arg5 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject)

FOUNDATION_EXPORT void ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject_initWithJavaUtilSpliterator_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject *self, id<JavaUtilSpliterator> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize);

FOUNDATION_EXPORT ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject *new_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject_initWithJavaUtilSpliterator_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject *create_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject_initWithJavaUtilSpliterator_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfObject)

#endif

#if !defined (ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive_) && (INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators || defined(INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive))
#define ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive_

#define RESTRICT_JavaUtilSpliterator 1
#define INCLUDE_JavaUtilSpliterator_OfPrimitive 1
#include "java/util/Spliterator.h"

@protocol ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilSpliterator;

/*!
 @brief Implementation of <code>Stream.flatMap</code> with a primitive spliterator output type.
 */
@interface ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive : ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator < JavaUtilSpliterator_OfPrimitive >

#pragma mark Public

- (void)forEachRemainingWithId:(id __nonnull)action;

- (jboolean)tryAdvanceWithId:(id __nonnull)action;

#pragma mark Package-Private

- (instancetype __nonnull)initWithJavaUtilSpliterator_OfPrimitive:(id<JavaUtilSpliterator_OfPrimitive> __nonnull)prefix
                                          withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)from
                                     withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
withComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory:(id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory> __nonnull)factory
                                                          withInt:(jint)characteristics
                                                         withLong:(jlong)estimatedSize;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)arg0
                              withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)arg1
                         withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)arg2
withComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory:(id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory> __nonnull)arg3
                                              withInt:(jint)arg4
                                             withLong:(jlong)arg5 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive)

FOUNDATION_EXPORT void ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive_initWithJavaUtilSpliterator_OfPrimitive_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory_withInt_withLong_(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive *self, id<JavaUtilSpliterator_OfPrimitive> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory> factory, jint characteristics, jlong estimatedSize);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive)

#endif

#if !defined (ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt_) && (INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators || defined(INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt))
#define ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt_

#define RESTRICT_JavaUtilSpliterator 1
#define INCLUDE_JavaUtilSpliterator_OfInt 1
#include "java/util/Spliterator.h"

@protocol ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilSpliterator;
@protocol JavaUtilSpliterator_OfPrimitive;

/*!
 @brief Implementation of <code>flatMapToInt</code>.
 */
@interface ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt : ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive < JavaUtilSpliterator_OfInt >

#pragma mark Package-Private

- (instancetype __nonnull)initWithJavaUtilSpliterator_OfInt:(id<JavaUtilSpliterator_OfInt> __nonnull)prefix
                                    withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)from
                               withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
                                                    withInt:(jint)characteristics
                                                   withLong:(jlong)estimatedSize;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithJavaUtilSpliterator_OfPrimitive:(id<JavaUtilSpliterator_OfPrimitive> __nonnull)arg0
                                          withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)arg1
                                     withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)arg2
withComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory:(id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory> __nonnull)arg3
                                                          withInt:(jint)arg4
                                                         withLong:(jlong)arg5 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt)

FOUNDATION_EXPORT void ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt_initWithJavaUtilSpliterator_OfInt_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt *self, id<JavaUtilSpliterator_OfInt> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize);

FOUNDATION_EXPORT ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt *new_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt_initWithJavaUtilSpliterator_OfInt_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator_OfInt> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt *create_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt_initWithJavaUtilSpliterator_OfInt_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator_OfInt> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfInt)

#endif

#if !defined (ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong_) && (INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators || defined(INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong))
#define ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong_

#define RESTRICT_JavaUtilSpliterator 1
#define INCLUDE_JavaUtilSpliterator_OfLong 1
#include "java/util/Spliterator.h"

@protocol ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilSpliterator;
@protocol JavaUtilSpliterator_OfPrimitive;

/*!
 @brief Implementation of <code>flatMapToLong</code>.
 */
@interface ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong : ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive < JavaUtilSpliterator_OfLong >

#pragma mark Package-Private

- (instancetype __nonnull)initWithJavaUtilSpliterator_OfLong:(id<JavaUtilSpliterator_OfLong> __nonnull)prefix
                                     withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)from
                                withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
                                                     withInt:(jint)characteristics
                                                    withLong:(jlong)estimatedSize;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithJavaUtilSpliterator_OfPrimitive:(id<JavaUtilSpliterator_OfPrimitive> __nonnull)arg0
                                          withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)arg1
                                     withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)arg2
withComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory:(id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory> __nonnull)arg3
                                                          withInt:(jint)arg4
                                                         withLong:(jlong)arg5 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong)

FOUNDATION_EXPORT void ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong_initWithJavaUtilSpliterator_OfLong_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong *self, id<JavaUtilSpliterator_OfLong> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize);

FOUNDATION_EXPORT ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong *new_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong_initWithJavaUtilSpliterator_OfLong_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator_OfLong> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong *create_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong_initWithJavaUtilSpliterator_OfLong_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator_OfLong> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfLong)

#endif

#if !defined (ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble_) && (INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators || defined(INCLUDE_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble))
#define ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble_

#define RESTRICT_JavaUtilSpliterator 1
#define INCLUDE_JavaUtilSpliterator_OfDouble 1
#include "java/util/Spliterator.h"

@protocol ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilSpliterator;
@protocol JavaUtilSpliterator_OfPrimitive;

/*!
 @brief Implementation of <code>flatMapToDouble</code>.
 */
@interface ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble : ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfPrimitive < JavaUtilSpliterator_OfDouble >

#pragma mark Package-Private

- (instancetype __nonnull)initWithJavaUtilSpliterator_OfDouble:(id<JavaUtilSpliterator_OfDouble> __nonnull)prefix
                                       withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)from
                                  withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)function
                                                       withInt:(jint)characteristics
                                                      withLong:(jlong)estimatedSize;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithJavaUtilSpliterator_OfPrimitive:(id<JavaUtilSpliterator_OfPrimitive> __nonnull)arg0
                                          withJavaUtilSpliterator:(id<JavaUtilSpliterator> __nonnull)arg1
                                     withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction> __nonnull)arg2
withComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory:(id<ComGoogleCommonCollectCollectSpliterators_FlatMapSpliterator_Factory> __nonnull)arg3
                                                          withInt:(jint)arg4
                                                         withLong:(jlong)arg5 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble)

FOUNDATION_EXPORT void ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble_initWithJavaUtilSpliterator_OfDouble_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble *self, id<JavaUtilSpliterator_OfDouble> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize);

FOUNDATION_EXPORT ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble *new_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble_initWithJavaUtilSpliterator_OfDouble_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator_OfDouble> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble *create_ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble_initWithJavaUtilSpliterator_OfDouble_withJavaUtilSpliterator_withJavaUtilFunctionFunction_withInt_withLong_(id<JavaUtilSpliterator_OfDouble> prefix, id<JavaUtilSpliterator> from, id<JavaUtilFunctionFunction> function, jint characteristics, jlong estimatedSize);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectCollectSpliterators_FlatMapSpliteratorOfDouble)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectCollectSpliterators")
