//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/build_result/java/com/google/common/primitives/FloatsMethodsForWeb.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonPrimitivesFloatsMethodsForWeb")
#ifdef RESTRICT_ComGoogleCommonPrimitivesFloatsMethodsForWeb
#define INCLUDE_ALL_ComGoogleCommonPrimitivesFloatsMethodsForWeb 0
#else
#define INCLUDE_ALL_ComGoogleCommonPrimitivesFloatsMethodsForWeb 1
#endif
#undef RESTRICT_ComGoogleCommonPrimitivesFloatsMethodsForWeb

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonPrimitivesFloatsMethodsForWeb_) && (INCLUDE_ALL_ComGoogleCommonPrimitivesFloatsMethodsForWeb || defined(INCLUDE_ComGoogleCommonPrimitivesFloatsMethodsForWeb))
#define ComGoogleCommonPrimitivesFloatsMethodsForWeb_

/*!
 @brief Holder for web specializations of methods of <code>Floats</code>.Intended to be empty for regular
  version.
 */
@interface ComGoogleCommonPrimitivesFloatsMethodsForWeb : NSObject

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivate;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonPrimitivesFloatsMethodsForWeb)

FOUNDATION_EXPORT void ComGoogleCommonPrimitivesFloatsMethodsForWeb_initPackagePrivate(ComGoogleCommonPrimitivesFloatsMethodsForWeb *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonPrimitivesFloatsMethodsForWeb)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonPrimitivesFloatsMethodsForWeb")
