//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/build_result/java/com/google/common/primitives/IntsMethodsForWeb.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonPrimitivesIntsMethodsForWeb")
#ifdef RESTRICT_ComGoogleCommonPrimitivesIntsMethodsForWeb
#define INCLUDE_ALL_ComGoogleCommonPrimitivesIntsMethodsForWeb 0
#else
#define INCLUDE_ALL_ComGoogleCommonPrimitivesIntsMethodsForWeb 1
#endif
#undef RESTRICT_ComGoogleCommonPrimitivesIntsMethodsForWeb

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonPrimitivesIntsMethodsForWeb_) && (INCLUDE_ALL_ComGoogleCommonPrimitivesIntsMethodsForWeb || defined(INCLUDE_ComGoogleCommonPrimitivesIntsMethodsForWeb))
#define ComGoogleCommonPrimitivesIntsMethodsForWeb_

/*!
 @brief Holder for web specializations of methods of <code>Ints</code>.Intended to be empty for regular
  version.
 */
@interface ComGoogleCommonPrimitivesIntsMethodsForWeb : NSObject

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivate;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonPrimitivesIntsMethodsForWeb)

FOUNDATION_EXPORT void ComGoogleCommonPrimitivesIntsMethodsForWeb_initPackagePrivate(ComGoogleCommonPrimitivesIntsMethodsForWeb *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonPrimitivesIntsMethodsForWeb)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonPrimitivesIntsMethodsForWeb")
