//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/build_result/java/com/google/common/primitives/ShortsMethodsForWeb.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonPrimitivesShortsMethodsForWeb")
#ifdef RESTRICT_ComGoogleCommonPrimitivesShortsMethodsForWeb
#define INCLUDE_ALL_ComGoogleCommonPrimitivesShortsMethodsForWeb 0
#else
#define INCLUDE_ALL_ComGoogleCommonPrimitivesShortsMethodsForWeb 1
#endif
#undef RESTRICT_ComGoogleCommonPrimitivesShortsMethodsForWeb

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonPrimitivesShortsMethodsForWeb_) && (INCLUDE_ALL_ComGoogleCommonPrimitivesShortsMethodsForWeb || defined(INCLUDE_ComGoogleCommonPrimitivesShortsMethodsForWeb))
#define ComGoogleCommonPrimitivesShortsMethodsForWeb_

/*!
 @brief Holder for web specializations of methods of <code>Shorts</code>.Intended to be empty for regular
  version.
 */
@interface ComGoogleCommonPrimitivesShortsMethodsForWeb : NSObject

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivate;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonPrimitivesShortsMethodsForWeb)

FOUNDATION_EXPORT void ComGoogleCommonPrimitivesShortsMethodsForWeb_initPackagePrivate(ComGoogleCommonPrimitivesShortsMethodsForWeb *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonPrimitivesShortsMethodsForWeb)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonPrimitivesShortsMethodsForWeb")
