//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/runners/model/FrameworkMember.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember")
#ifdef RESTRICT_OrgJunitRunnersModelFrameworkMember
#define INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember 0
#else
#define INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember 1
#endif
#undef RESTRICT_OrgJunitRunnersModelFrameworkMember

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitRunnersModelFrameworkMember_) && (INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember || defined(INCLUDE_OrgJunitRunnersModelFrameworkMember))
#define OrgJunitRunnersModelFrameworkMember_

#define RESTRICT_OrgJunitRunnersModelAnnotatable 1
#define INCLUDE_OrgJunitRunnersModelAnnotatable 1
#include "org/junit/runners/model/Annotatable.h"

@class IOSClass;
@protocol JavaUtilList;

/*!
 @brief Parent class for <code>FrameworkField</code> and <code>FrameworkMethod</code>
 @since 4.7
 */
@interface OrgJunitRunnersModelFrameworkMember : NSObject < OrgJunitRunnersModelAnnotatable >

#pragma mark Public

- (instancetype __nonnull)init;

- (IOSClass *)getDeclaringClass;

- (NSString *)getName;

- (IOSClass *)getType;

/*!
 @brief Returns true if this member is public, false if not.
 */
- (jboolean)isPublic;

/*!
 @brief Returns true if this member is static, false if not.
 */
- (jboolean)isStatic;

#pragma mark Protected

- (jint)getModifiers;

#pragma mark Package-Private

- (OrgJunitRunnersModelFrameworkMember *)handlePossibleBridgeMethodWithJavaUtilList:(id<JavaUtilList>)members;

- (jboolean)isBridgeMethod;

- (jboolean)isShadowedByWithOrgJunitRunnersModelFrameworkMember:(OrgJunitRunnersModelFrameworkMember *)otherMember;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnersModelFrameworkMember)

FOUNDATION_EXPORT void OrgJunitRunnersModelFrameworkMember_init(OrgJunitRunnersModelFrameworkMember *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnersModelFrameworkMember)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember")
