//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/runners/model/InvalidTestClassError.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnersModelInvalidTestClassError")
#ifdef RESTRICT_OrgJunitRunnersModelInvalidTestClassError
#define INCLUDE_ALL_OrgJunitRunnersModelInvalidTestClassError 0
#else
#define INCLUDE_ALL_OrgJunitRunnersModelInvalidTestClassError 1
#endif
#undef RESTRICT_OrgJunitRunnersModelInvalidTestClassError

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitRunnersModelInvalidTestClassError_) && (INCLUDE_ALL_OrgJunitRunnersModelInvalidTestClassError || defined(INCLUDE_OrgJunitRunnersModelInvalidTestClassError))
#define OrgJunitRunnersModelInvalidTestClassError_

#define RESTRICT_OrgJunitRunnersModelInitializationError 1
#define INCLUDE_OrgJunitRunnersModelInitializationError 1
#include "org/junit/runners/model/InitializationError.h"

@class IOSClass;
@class JavaLangThrowable;
@protocol JavaUtilList;

/*!
 @brief Thrown by <code>org.junit.runner.Runner</code>s in case the class under test is not valid.
 <p>
  Its message conveniently lists all of the validation errors.
 @since 4.13
 */
@interface OrgJunitRunnersModelInvalidTestClassError : OrgJunitRunnersModelInitializationError

#pragma mark Public

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)offendingTestClass
                          withJavaUtilList:(id<JavaUtilList>)validationErrors;

/*!
 @return a message with a list of all of the validation errors
 */
- (NSString *)getMessage;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithJavaUtilList:(id<JavaUtilList>)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnersModelInvalidTestClassError)

FOUNDATION_EXPORT void OrgJunitRunnersModelInvalidTestClassError_initWithIOSClass_withJavaUtilList_(OrgJunitRunnersModelInvalidTestClassError *self, IOSClass *offendingTestClass, id<JavaUtilList> validationErrors);

FOUNDATION_EXPORT OrgJunitRunnersModelInvalidTestClassError *new_OrgJunitRunnersModelInvalidTestClassError_initWithIOSClass_withJavaUtilList_(IOSClass *offendingTestClass, id<JavaUtilList> validationErrors) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitRunnersModelInvalidTestClassError *create_OrgJunitRunnersModelInvalidTestClassError_initWithIOSClass_withJavaUtilList_(IOSClass *offendingTestClass, id<JavaUtilList> validationErrors);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnersModelInvalidTestClassError)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnersModelInvalidTestClassError")
