//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/internal/management/FakeThreadMXBean.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitInternalManagementFakeThreadMXBean")
#ifdef RESTRICT_OrgJunitInternalManagementFakeThreadMXBean
#define INCLUDE_ALL_OrgJunitInternalManagementFakeThreadMXBean 0
#else
#define INCLUDE_ALL_OrgJunitInternalManagementFakeThreadMXBean 1
#endif
#undef RESTRICT_OrgJunitInternalManagementFakeThreadMXBean

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitInternalManagementFakeThreadMXBean_) && (INCLUDE_ALL_OrgJunitInternalManagementFakeThreadMXBean || defined(INCLUDE_OrgJunitInternalManagementFakeThreadMXBean))
#define OrgJunitInternalManagementFakeThreadMXBean_

#define RESTRICT_OrgJunitInternalManagementThreadMXBean 1
#define INCLUDE_OrgJunitInternalManagementThreadMXBean 1
#include "org/junit/internal/management/ThreadMXBean.h"

/*!
 @brief No-op implementation of ThreadMXBean when the platform doesn't provide it.
 */
@interface OrgJunitInternalManagementFakeThreadMXBean : NSObject < OrgJunitInternalManagementThreadMXBean >

#pragma mark Public

/*!
 @brief <p>Always throws an <code>UnsupportedOperationException</code>
 */
- (jlong)getThreadCpuTimeWithLong:(jlong)id_;

/*!
 @brief <p>Always returns false.
 */
- (jboolean)isThreadCpuTimeSupported;

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivate;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitInternalManagementFakeThreadMXBean)

FOUNDATION_EXPORT void OrgJunitInternalManagementFakeThreadMXBean_initPackagePrivate(OrgJunitInternalManagementFakeThreadMXBean *self);

FOUNDATION_EXPORT OrgJunitInternalManagementFakeThreadMXBean *new_OrgJunitInternalManagementFakeThreadMXBean_initPackagePrivate(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitInternalManagementFakeThreadMXBean *create_OrgJunitInternalManagementFakeThreadMXBean_initPackagePrivate(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalManagementFakeThreadMXBean)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitInternalManagementFakeThreadMXBean")
