//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/internal/management/FakeRuntimeMXBean.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitInternalManagementFakeRuntimeMXBean")
#ifdef RESTRICT_OrgJunitInternalManagementFakeRuntimeMXBean
#define INCLUDE_ALL_OrgJunitInternalManagementFakeRuntimeMXBean 0
#else
#define INCLUDE_ALL_OrgJunitInternalManagementFakeRuntimeMXBean 1
#endif
#undef RESTRICT_OrgJunitInternalManagementFakeRuntimeMXBean

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitInternalManagementFakeRuntimeMXBean_) && (INCLUDE_ALL_OrgJunitInternalManagementFakeRuntimeMXBean || defined(INCLUDE_OrgJunitInternalManagementFakeRuntimeMXBean))
#define OrgJunitInternalManagementFakeRuntimeMXBean_

#define RESTRICT_OrgJunitInternalManagementRuntimeMXBean 1
#define INCLUDE_OrgJunitInternalManagementRuntimeMXBean 1
#include "org/junit/internal/management/RuntimeMXBean.h"

@protocol JavaUtilList;

/*!
 @brief No-op implementation of RuntimeMXBean when the platform doesn't provide it.
 */
@interface OrgJunitInternalManagementFakeRuntimeMXBean : NSObject < OrgJunitInternalManagementRuntimeMXBean >

#pragma mark Public

/*!
 @brief <p>Always returns an empty list.
 */
- (id<JavaUtilList>)getInputArguments;

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivate;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitInternalManagementFakeRuntimeMXBean)

FOUNDATION_EXPORT void OrgJunitInternalManagementFakeRuntimeMXBean_initPackagePrivate(OrgJunitInternalManagementFakeRuntimeMXBean *self);

FOUNDATION_EXPORT OrgJunitInternalManagementFakeRuntimeMXBean *new_OrgJunitInternalManagementFakeRuntimeMXBean_initPackagePrivate(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitInternalManagementFakeRuntimeMXBean *create_OrgJunitInternalManagementFakeRuntimeMXBean_initPackagePrivate(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalManagementFakeRuntimeMXBean)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitInternalManagementFakeRuntimeMXBean")
