//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/internal/management/RuntimeMXBean.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitInternalManagementRuntimeMXBean")
#ifdef RESTRICT_OrgJunitInternalManagementRuntimeMXBean
#define INCLUDE_ALL_OrgJunitInternalManagementRuntimeMXBean 0
#else
#define INCLUDE_ALL_OrgJunitInternalManagementRuntimeMXBean 1
#endif
#undef RESTRICT_OrgJunitInternalManagementRuntimeMXBean

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitInternalManagementRuntimeMXBean_) && (INCLUDE_ALL_OrgJunitInternalManagementRuntimeMXBean || defined(INCLUDE_OrgJunitInternalManagementRuntimeMXBean))
#define OrgJunitInternalManagementRuntimeMXBean_

@protocol JavaUtilList;

/*!
 @brief Wrapper for <code>java.lang.management.RuntimeMXBean</code>.
 */
@protocol OrgJunitInternalManagementRuntimeMXBean < JavaObject >

/*!
 - seealso: java.lang.management.RuntimeMXBean#getInputArguments()
 */
- (id<JavaUtilList>)getInputArguments;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitInternalManagementRuntimeMXBean)

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalManagementRuntimeMXBean)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitInternalManagementRuntimeMXBean")
