//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/android/build_result/java/com/google/common/primitives/DoublesMethodsForWeb.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonPrimitivesDoublesMethodsForWeb")
#ifdef RESTRICT_ComGoogleCommonPrimitivesDoublesMethodsForWeb
#define INCLUDE_ALL_ComGoogleCommonPrimitivesDoublesMethodsForWeb 0
#else
#define INCLUDE_ALL_ComGoogleCommonPrimitivesDoublesMethodsForWeb 1
#endif
#undef RESTRICT_ComGoogleCommonPrimitivesDoublesMethodsForWeb

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonPrimitivesDoublesMethodsForWeb_) && (INCLUDE_ALL_ComGoogleCommonPrimitivesDoublesMethodsForWeb || defined(INCLUDE_ComGoogleCommonPrimitivesDoublesMethodsForWeb))
#define ComGoogleCommonPrimitivesDoublesMethodsForWeb_

/*!
 @brief Holder for web specializations of methods of <code>Doubles</code>.Intended to be empty for regular
  version.
 */
@interface ComGoogleCommonPrimitivesDoublesMethodsForWeb : NSObject

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivate;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonPrimitivesDoublesMethodsForWeb)

FOUNDATION_EXPORT void ComGoogleCommonPrimitivesDoublesMethodsForWeb_initPackagePrivate(ComGoogleCommonPrimitivesDoublesMethodsForWeb *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonPrimitivesDoublesMethodsForWeb)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonPrimitivesDoublesMethodsForWeb")
