//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/android/build_result/java/com/google/common/graph/ImmutableGraph.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonGraphImmutableGraph")
#ifdef RESTRICT_ComGoogleCommonGraphImmutableGraph
#define INCLUDE_ALL_ComGoogleCommonGraphImmutableGraph 0
#else
#define INCLUDE_ALL_ComGoogleCommonGraphImmutableGraph 1
#endif
#undef RESTRICT_ComGoogleCommonGraphImmutableGraph

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonGraphImmutableGraph_) && (INCLUDE_ALL_ComGoogleCommonGraphImmutableGraph || defined(INCLUDE_ComGoogleCommonGraphImmutableGraph))
#define ComGoogleCommonGraphImmutableGraph_

#define RESTRICT_ComGoogleCommonGraphForwardingGraph 1
#define INCLUDE_ComGoogleCommonGraphForwardingGraph 1
#include "com/google/common/graph/ForwardingGraph.h"

@class ComGoogleCommonGraphElementOrder;
@protocol ComGoogleCommonGraphBaseGraph;
@protocol ComGoogleCommonGraphGraph;

/*!
 @brief A <code>Graph</code> whose elements and structural relationships will never change.Instances of this
  class may be obtained with <code>copyOf(Graph)</code>.
 <p>See the Guava User's Guide's <a href="https://github.com/google/guava/wiki/GraphsExplained#immutable-implementations">
 discussion
  of the <code>Immutable*</code> types</a> for more information on the properties and guarantees
  provided by this class.
 @author James Sexton
 @author Joshua O'Madadhain
 @author Omar Darwish
 @author Jens Nyman
 @since 20.0
 */
@interface ComGoogleCommonGraphImmutableGraph : ComGoogleCommonGraphForwardingGraph

#pragma mark Public

/*!
 @brief Returns an immutable copy of <code>graph</code>.
 */
+ (ComGoogleCommonGraphImmutableGraph *)copyOfWithComGoogleCommonGraphGraph:(id<ComGoogleCommonGraphGraph> __nonnull)graph OBJC_METHOD_FAMILY_NONE;

/*!
 @brief Simply returns its argument.
 */
+ (ComGoogleCommonGraphImmutableGraph *)copyOfWithComGoogleCommonGraphImmutableGraph:(ComGoogleCommonGraphImmutableGraph * __nonnull)graph OBJC_METHOD_FAMILY_NONE __attribute__((deprecated));

- (ComGoogleCommonGraphElementOrder *)incidentEdgeOrder;

#pragma mark Protected

- (id<ComGoogleCommonGraphBaseGraph>)delegate;

#pragma mark Package-Private

- (instancetype __nonnull)initWithComGoogleCommonGraphBaseGraph:(id<ComGoogleCommonGraphBaseGraph> __nonnull)backingGraph;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initPackagePrivate NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonGraphImmutableGraph)

FOUNDATION_EXPORT void ComGoogleCommonGraphImmutableGraph_initWithComGoogleCommonGraphBaseGraph_(ComGoogleCommonGraphImmutableGraph *self, id<ComGoogleCommonGraphBaseGraph> backingGraph);

FOUNDATION_EXPORT ComGoogleCommonGraphImmutableGraph *new_ComGoogleCommonGraphImmutableGraph_initWithComGoogleCommonGraphBaseGraph_(id<ComGoogleCommonGraphBaseGraph> backingGraph) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonGraphImmutableGraph *create_ComGoogleCommonGraphImmutableGraph_initWithComGoogleCommonGraphBaseGraph_(id<ComGoogleCommonGraphBaseGraph> backingGraph);

FOUNDATION_EXPORT ComGoogleCommonGraphImmutableGraph *ComGoogleCommonGraphImmutableGraph_copyOfWithComGoogleCommonGraphGraph_(id<ComGoogleCommonGraphGraph> graph);

FOUNDATION_EXPORT ComGoogleCommonGraphImmutableGraph *ComGoogleCommonGraphImmutableGraph_copyOfWithComGoogleCommonGraphImmutableGraph_(ComGoogleCommonGraphImmutableGraph *graph);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonGraphImmutableGraph)

#endif

#if !defined (ComGoogleCommonGraphImmutableGraph_Builder_) && (INCLUDE_ALL_ComGoogleCommonGraphImmutableGraph || defined(INCLUDE_ComGoogleCommonGraphImmutableGraph_Builder))
#define ComGoogleCommonGraphImmutableGraph_Builder_

@class ComGoogleCommonGraphEndpointPair;
@class ComGoogleCommonGraphGraphBuilder;
@class ComGoogleCommonGraphImmutableGraph;

/*!
 @brief A builder for creating <code>ImmutableGraph</code> instances, especially <code>static final</code>
  graphs.Example:
  
 @code
 static final ImmutableGraph<Country> COUNTRY_ADJACENCY_GRAPH =
      GraphBuilder.undirected()
          .
 <Country>immutable()
          .putEdge(FRANCE, GERMANY)
          .putEdge(FRANCE, BELGIUM)
          .putEdge(GERMANY, BELGIUM)
          .addNode(ICELAND)
          .build(); 
 
@endcode
  
 <p>Builder instances can be reused; it is safe to call <code>build</code> multiple times to build
  multiple graphs in series. Each new graph contains all the elements of the ones created before
  it.
 @since 28.0
 */
@interface ComGoogleCommonGraphImmutableGraph_Builder : NSObject

#pragma mark Public

/*!
 @brief Adds <code>node</code> if it is not already present.
 <p><b>Nodes must be unique</b>, just as <code>Map</code> keys must be. They must also be non-null.
 @return this <code>Builder</code> object
 */
- (ComGoogleCommonGraphImmutableGraph_Builder *)addNodeWithId:(id __nonnull)node;

/*!
 @brief Returns a newly-created <code>ImmutableGraph</code> based on the contents of this <code>Builder</code>.
 */
- (ComGoogleCommonGraphImmutableGraph *)build;

/*!
 @brief Adds an edge connecting <code>endpoints</code> (in the order, if any, specified by <code>endpoints</code>
 ) if one is not already present.
 <p>If this graph is directed, <code>endpoints</code> must be ordered and the added edge will be
  directed; if it is undirected, the added edge will be undirected. 
 <p>If this graph is directed, <code>endpoints</code> must be ordered. 
 <p>If either or both endpoints are not already present in this graph, this method will
  silently <code>add</code> each missing endpoint to the graph.
 @return this <code>Builder</code> object
 @throw IllegalArgumentExceptionif the introduction of the edge would violate <code>allowsSelfLoops()</code>
 @throw IllegalArgumentExceptionif the endpoints are unordered and the graph is directed
 */
- (ComGoogleCommonGraphImmutableGraph_Builder *)putEdgeWithComGoogleCommonGraphEndpointPair:(ComGoogleCommonGraphEndpointPair * __nonnull)endpoints;

/*!
 @brief Adds an edge connecting <code>nodeU</code> to <code>nodeV</code> if one is not already present.
 <p>If the graph is directed, the resultant edge will be directed; otherwise, it will be
  undirected. 
 <p>If <code>nodeU</code> and <code>nodeV</code> are not already present in this graph, this method will
  silently <code>add</code> <code>nodeU</code> and <code>nodeV</code> to the graph.
 @return this <code>Builder</code> object
 @throw IllegalArgumentExceptionif the introduction of the edge would violate <code>allowsSelfLoops()</code>
 */
- (ComGoogleCommonGraphImmutableGraph_Builder *)putEdgeWithId:(id __nonnull)nodeU
                                                       withId:(id __nonnull)nodeV;

#pragma mark Package-Private

- (instancetype __nonnull)initWithComGoogleCommonGraphGraphBuilder:(ComGoogleCommonGraphGraphBuilder * __nonnull)graphBuilder;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonGraphImmutableGraph_Builder)

FOUNDATION_EXPORT void ComGoogleCommonGraphImmutableGraph_Builder_initWithComGoogleCommonGraphGraphBuilder_(ComGoogleCommonGraphImmutableGraph_Builder *self, ComGoogleCommonGraphGraphBuilder *graphBuilder);

FOUNDATION_EXPORT ComGoogleCommonGraphImmutableGraph_Builder *new_ComGoogleCommonGraphImmutableGraph_Builder_initWithComGoogleCommonGraphGraphBuilder_(ComGoogleCommonGraphGraphBuilder *graphBuilder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonGraphImmutableGraph_Builder *create_ComGoogleCommonGraphImmutableGraph_Builder_initWithComGoogleCommonGraphGraphBuilder_(ComGoogleCommonGraphGraphBuilder *graphBuilder);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonGraphImmutableGraph_Builder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonGraphImmutableGraph")
