//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/android/build_result/java/com/google/common/graph/StandardMutableValueGraph.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonGraphStandardMutableValueGraph")
#ifdef RESTRICT_ComGoogleCommonGraphStandardMutableValueGraph
#define INCLUDE_ALL_ComGoogleCommonGraphStandardMutableValueGraph 0
#else
#define INCLUDE_ALL_ComGoogleCommonGraphStandardMutableValueGraph 1
#endif
#undef RESTRICT_ComGoogleCommonGraphStandardMutableValueGraph

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonGraphStandardMutableValueGraph_) && (INCLUDE_ALL_ComGoogleCommonGraphStandardMutableValueGraph || defined(INCLUDE_ComGoogleCommonGraphStandardMutableValueGraph))
#define ComGoogleCommonGraphStandardMutableValueGraph_

#define RESTRICT_ComGoogleCommonGraphStandardValueGraph 1
#define INCLUDE_ComGoogleCommonGraphStandardValueGraph 1
#include "com/google/common/graph/StandardValueGraph.h"

#define RESTRICT_ComGoogleCommonGraphMutableValueGraph 1
#define INCLUDE_ComGoogleCommonGraphMutableValueGraph 1
#include "com/google/common/graph/MutableValueGraph.h"

@class ComGoogleCommonGraphAbstractGraphBuilder;
@class ComGoogleCommonGraphElementOrder;
@class ComGoogleCommonGraphEndpointPair;
@protocol JavaUtilMap;

/*!
 @brief Standard implementation of <code>MutableValueGraph</code> that supports both directed and undirected
  graphs.Instances of this class should be constructed with <code>ValueGraphBuilder</code>.
 <p>Time complexities for mutation methods are all O(1) except for <code>removeNode(N node)</code>,
  which is in O(d_node) where d_node is the degree of <code>node</code>.
 @author James Sexton
 @author Joshua O'Madadhain
 @author Omar Darwish
 */
@interface ComGoogleCommonGraphStandardMutableValueGraph : ComGoogleCommonGraphStandardValueGraph < ComGoogleCommonGraphMutableValueGraph >

#pragma mark Public

- (jboolean)addNodeWithId:(id __nonnull)node;

- (ComGoogleCommonGraphElementOrder *)incidentEdgeOrder;

- (id)putEdgeValueWithComGoogleCommonGraphEndpointPair:(ComGoogleCommonGraphEndpointPair * __nonnull)endpoints
                                                withId:(id __nonnull)value;

- (id)putEdgeValueWithId:(id __nonnull)nodeU
                  withId:(id __nonnull)nodeV
                  withId:(id __nonnull)value;

- (id)removeEdgeWithComGoogleCommonGraphEndpointPair:(ComGoogleCommonGraphEndpointPair * __nonnull)endpoints;

- (id)removeEdgeWithId:(id __nonnull)nodeU
                withId:(id __nonnull)nodeV;

- (jboolean)removeNodeWithId:(id __nonnull)node;

#pragma mark Package-Private

/*!
 @brief Constructs a mutable graph with the properties specified in <code>builder</code>.
 */
- (instancetype __nonnull)initPackagePrivateWithComGoogleCommonGraphAbstractGraphBuilder:(ComGoogleCommonGraphAbstractGraphBuilder * __nonnull)builder;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initPackagePrivateWithComGoogleCommonGraphAbstractGraphBuilder:(ComGoogleCommonGraphAbstractGraphBuilder * __nonnull)arg0
                                                                         withJavaUtilMap:(id<JavaUtilMap> __nonnull)arg1
                                                                                withLong:(jlong)arg2 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonGraphStandardMutableValueGraph)

FOUNDATION_EXPORT void ComGoogleCommonGraphStandardMutableValueGraph_initPackagePrivateWithComGoogleCommonGraphAbstractGraphBuilder_(ComGoogleCommonGraphStandardMutableValueGraph *self, ComGoogleCommonGraphAbstractGraphBuilder *builder);

FOUNDATION_EXPORT ComGoogleCommonGraphStandardMutableValueGraph *new_ComGoogleCommonGraphStandardMutableValueGraph_initPackagePrivateWithComGoogleCommonGraphAbstractGraphBuilder_(ComGoogleCommonGraphAbstractGraphBuilder *builder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonGraphStandardMutableValueGraph *create_ComGoogleCommonGraphStandardMutableValueGraph_initPackagePrivateWithComGoogleCommonGraphAbstractGraphBuilder_(ComGoogleCommonGraphAbstractGraphBuilder *builder);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonGraphStandardMutableValueGraph)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonGraphStandardMutableValueGraph")
