//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/android/build_result/java/com/google/common/graph/StandardMutableGraph.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonGraphStandardMutableGraph")
#ifdef RESTRICT_ComGoogleCommonGraphStandardMutableGraph
#define INCLUDE_ALL_ComGoogleCommonGraphStandardMutableGraph 0
#else
#define INCLUDE_ALL_ComGoogleCommonGraphStandardMutableGraph 1
#endif
#undef RESTRICT_ComGoogleCommonGraphStandardMutableGraph

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonGraphStandardMutableGraph_) && (INCLUDE_ALL_ComGoogleCommonGraphStandardMutableGraph || defined(INCLUDE_ComGoogleCommonGraphStandardMutableGraph))
#define ComGoogleCommonGraphStandardMutableGraph_

#define RESTRICT_ComGoogleCommonGraphForwardingGraph 1
#define INCLUDE_ComGoogleCommonGraphForwardingGraph 1
#include "com/google/common/graph/ForwardingGraph.h"

#define RESTRICT_ComGoogleCommonGraphMutableGraph 1
#define INCLUDE_ComGoogleCommonGraphMutableGraph 1
#include "com/google/common/graph/MutableGraph.h"

@class ComGoogleCommonGraphAbstractGraphBuilder;
@class ComGoogleCommonGraphEndpointPair;
@protocol ComGoogleCommonGraphBaseGraph;

/*!
 @brief Standard implementation of <code>MutableGraph</code> that supports both directed and undirected
  graphs.Instances of this class should be constructed with <code>GraphBuilder</code>.
 <p>Time complexities for mutation methods are all O(1) except for <code>removeNode(N node)</code>,
  which is in O(d_node) where d_node is the degree of <code>node</code>.
 @author James Sexton
 */
@interface ComGoogleCommonGraphStandardMutableGraph : ComGoogleCommonGraphForwardingGraph < ComGoogleCommonGraphMutableGraph >

#pragma mark Public

- (jboolean)addNodeWithId:(id __nonnull)node;

- (jboolean)putEdgeWithComGoogleCommonGraphEndpointPair:(ComGoogleCommonGraphEndpointPair * __nonnull)endpoints;

- (jboolean)putEdgeWithId:(id __nonnull)nodeU
                   withId:(id __nonnull)nodeV;

- (jboolean)removeEdgeWithComGoogleCommonGraphEndpointPair:(ComGoogleCommonGraphEndpointPair * __nonnull)endpoints;

- (jboolean)removeEdgeWithId:(id __nonnull)nodeU
                      withId:(id __nonnull)nodeV;

- (jboolean)removeNodeWithId:(id __nonnull)node;

#pragma mark Protected

- (id<ComGoogleCommonGraphBaseGraph>)delegate;

#pragma mark Package-Private

/*!
 @brief Constructs a <code>MutableGraph</code> with the properties specified in <code>builder</code>.
 */
- (instancetype __nonnull)initPackagePrivateWithComGoogleCommonGraphAbstractGraphBuilder:(ComGoogleCommonGraphAbstractGraphBuilder * __nonnull)builder;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initPackagePrivate NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonGraphStandardMutableGraph)

FOUNDATION_EXPORT void ComGoogleCommonGraphStandardMutableGraph_initPackagePrivateWithComGoogleCommonGraphAbstractGraphBuilder_(ComGoogleCommonGraphStandardMutableGraph *self, ComGoogleCommonGraphAbstractGraphBuilder *builder);

FOUNDATION_EXPORT ComGoogleCommonGraphStandardMutableGraph *new_ComGoogleCommonGraphStandardMutableGraph_initPackagePrivateWithComGoogleCommonGraphAbstractGraphBuilder_(ComGoogleCommonGraphAbstractGraphBuilder *builder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonGraphStandardMutableGraph *create_ComGoogleCommonGraphStandardMutableGraph_initPackagePrivateWithComGoogleCommonGraphAbstractGraphBuilder_(ComGoogleCommonGraphAbstractGraphBuilder *builder);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonGraphStandardMutableGraph)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonGraphStandardMutableGraph")
