//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/validator/TestClassValidator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitValidatorTestClassValidator")
#ifdef RESTRICT_OrgJunitValidatorTestClassValidator
#define INCLUDE_ALL_OrgJunitValidatorTestClassValidator 0
#else
#define INCLUDE_ALL_OrgJunitValidatorTestClassValidator 1
#endif
#undef RESTRICT_OrgJunitValidatorTestClassValidator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitValidatorTestClassValidator_) && (INCLUDE_ALL_OrgJunitValidatorTestClassValidator || defined(INCLUDE_OrgJunitValidatorTestClassValidator))
#define OrgJunitValidatorTestClassValidator_

@class OrgJunitRunnersModelTestClass;
@protocol JavaUtilList;

/*!
 @brief Validates a single facet of a test class.
 @since 4.12
 */
@protocol OrgJunitValidatorTestClassValidator < JavaObject >

/*!
 @brief Validate a single facet of a test class.
 @param testClass the 
 <code>TestClass</code>  that is validated.
 @return the validation errors found by the validator.
 */
- (id<JavaUtilList>)validateTestClassWithOrgJunitRunnersModelTestClass:(OrgJunitRunnersModelTestClass *)testClass;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitValidatorTestClassValidator)

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitValidatorTestClassValidator)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitValidatorTestClassValidator")
