//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/runners/parameterized/ParametersRunnerFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnersParameterizedParametersRunnerFactory")
#ifdef RESTRICT_OrgJunitRunnersParameterizedParametersRunnerFactory
#define INCLUDE_ALL_OrgJunitRunnersParameterizedParametersRunnerFactory 0
#else
#define INCLUDE_ALL_OrgJunitRunnersParameterizedParametersRunnerFactory 1
#endif
#undef RESTRICT_OrgJunitRunnersParameterizedParametersRunnerFactory

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitRunnersParameterizedParametersRunnerFactory_) && (INCLUDE_ALL_OrgJunitRunnersParameterizedParametersRunnerFactory || defined(INCLUDE_OrgJunitRunnersParameterizedParametersRunnerFactory))
#define OrgJunitRunnersParameterizedParametersRunnerFactory_

@class OrgJunitRunnerRunner;
@class OrgJunitRunnersParameterizedTestWithParameters;

/*!
 @brief A <code>ParametersRunnerFactory</code> creates a runner for a single 
 <code>TestWithParameters</code>.
 @since 4.12
 */
@protocol OrgJunitRunnersParameterizedParametersRunnerFactory < JavaObject >

/*!
 @brief Returns a runner for the specified <code>TestWithParameters</code>.
 @throw InitializationError
 if the runner could not be created.
 */
- (OrgJunitRunnerRunner *)createRunnerForTestWithParametersWithOrgJunitRunnersParameterizedTestWithParameters:(OrgJunitRunnersParameterizedTestWithParameters *)test;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnersParameterizedParametersRunnerFactory)

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnersParameterizedParametersRunnerFactory)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnersParameterizedParametersRunnerFactory")
