//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/internal/builders/AnnotatedBuilder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitInternalBuildersAnnotatedBuilder")
#ifdef RESTRICT_OrgJunitInternalBuildersAnnotatedBuilder
#define INCLUDE_ALL_OrgJunitInternalBuildersAnnotatedBuilder 0
#else
#define INCLUDE_ALL_OrgJunitInternalBuildersAnnotatedBuilder 1
#endif
#undef RESTRICT_OrgJunitInternalBuildersAnnotatedBuilder

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitInternalBuildersAnnotatedBuilder_) && (INCLUDE_ALL_OrgJunitInternalBuildersAnnotatedBuilder || defined(INCLUDE_OrgJunitInternalBuildersAnnotatedBuilder))
#define OrgJunitInternalBuildersAnnotatedBuilder_

#define RESTRICT_OrgJunitRunnersModelRunnerBuilder 1
#define INCLUDE_OrgJunitRunnersModelRunnerBuilder 1
#include "org/junit/runners/model/RunnerBuilder.h"

@class IOSClass;
@class OrgJunitRunnerRunner;

/*!
 @brief The <code>AnnotatedBuilder</code> is a strategy for constructing runners for test class that have been annotated with the 
 <code>@@RunWith</code> annotation.All tests within this class will be executed using the runner that was specified within
  the annotation.
 <p>
  If a runner supports inner member classes, the member classes will inherit the runner from the enclosing class, e.g.: 
 @code

   &#064;RunWith(MyRunner.class)
  public class MyTest {
      // some tests might go here
      public class MyMemberClass {
                  &#064;Test
          public void thisTestRunsWith_MyRunner() {
              // some test logic
          }
          // some more tests might go here
      }     
     &#064;RunWith(AnotherRunner.class)
      public class AnotherMemberClass {
          // some tests might go here
          public class DeepInnerClass {
                          &#064;Test
              public void thisTestRunsWith_AnotherRunner() {
                  // some test logic
              }            }
          public class DeepInheritedClass extends SuperTest {
                          &#064;Test
              public void thisTestRunsWith_SuperRunner() {
                  // some test logic
              }            }            }            }            
  &#064;RunWith(SuperRunner.class)
  public class SuperTest {
      // some tests might go here
  } 
  
@endcode
  The key points to note here are: 
 <ul>
      <li>If there is no RunWith annotation, no runner will be created.</li>
      <li>The resolve step is inside-out, e.g. the closest RunWith annotation wins</li>
      <li>RunWith annotations are inherited and work as if the class was annotated itself.</li>
      <li>The default JUnit runner does not support inner member classes,
          so this is only valid for custom runners that support inner member classes.</li>
      <li>Custom runners with support for inner classes may or may not support RunWith annotations for member
          classes. Please refer to the custom runner documentation.</li>
  </ul>
 - seealso: org.junit.runners.model.RunnerBuilder
 - seealso: org.junit.runner.RunWith
 @since 4.0
 */
@interface OrgJunitInternalBuildersAnnotatedBuilder : OrgJunitRunnersModelRunnerBuilder

#pragma mark Public

- (instancetype __nonnull)initWithOrgJunitRunnersModelRunnerBuilder:(OrgJunitRunnersModelRunnerBuilder *)suiteBuilder;

- (OrgJunitRunnerRunner *)buildRunnerWithIOSClass:(IOSClass *)runnerClass
                                     withIOSClass:(IOSClass *)testClass;

- (OrgJunitRunnerRunner *)runnerForClassWithIOSClass:(IOSClass *)testClass;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitInternalBuildersAnnotatedBuilder)

FOUNDATION_EXPORT void OrgJunitInternalBuildersAnnotatedBuilder_initWithOrgJunitRunnersModelRunnerBuilder_(OrgJunitInternalBuildersAnnotatedBuilder *self, OrgJunitRunnersModelRunnerBuilder *suiteBuilder);

FOUNDATION_EXPORT OrgJunitInternalBuildersAnnotatedBuilder *new_OrgJunitInternalBuildersAnnotatedBuilder_initWithOrgJunitRunnersModelRunnerBuilder_(OrgJunitRunnersModelRunnerBuilder *suiteBuilder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitInternalBuildersAnnotatedBuilder *create_OrgJunitInternalBuildersAnnotatedBuilder_initWithOrgJunitRunnersModelRunnerBuilder_(OrgJunitRunnersModelRunnerBuilder *suiteBuilder);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalBuildersAnnotatedBuilder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitInternalBuildersAnnotatedBuilder")
