//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/build_result/java/com/google/common/graph/GraphBuilder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonGraphGraphBuilder")
#ifdef RESTRICT_ComGoogleCommonGraphGraphBuilder
#define INCLUDE_ALL_ComGoogleCommonGraphGraphBuilder 0
#else
#define INCLUDE_ALL_ComGoogleCommonGraphGraphBuilder 1
#endif
#undef RESTRICT_ComGoogleCommonGraphGraphBuilder

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonGraphGraphBuilder_) && (INCLUDE_ALL_ComGoogleCommonGraphGraphBuilder || defined(INCLUDE_ComGoogleCommonGraphGraphBuilder))
#define ComGoogleCommonGraphGraphBuilder_

#define RESTRICT_ComGoogleCommonGraphAbstractGraphBuilder 1
#define INCLUDE_ComGoogleCommonGraphAbstractGraphBuilder 1
#include "com/google/common/graph/AbstractGraphBuilder.h"

@class ComGoogleCommonGraphElementOrder;
@class ComGoogleCommonGraphImmutableGraph_Builder;
@protocol ComGoogleCommonGraphGraph;
@protocol ComGoogleCommonGraphMutableGraph;

/*!
 @brief A builder for constructing instances of <code>MutableGraph</code> or <code>ImmutableGraph</code> with
  user-defined properties.
 <p>A graph built by this class will have the following properties by default: 
 <ul>
    <li>does not allow self-loops
    <li>orders <code>Graph.nodes()</code> in the order in which the elements were added 
 </ul>
  
 <p>Examples of use: 
 @code
 // Building a mutable graph
  MutableGraph<String> graph = GraphBuilder.undirected().allowsSelfLoops(true).build();
  graph.putEdge("bread", "bread");
  graph.putEdge("chocolate", "peanut butter");
  graph.putEdge("peanut butter", "jelly");
  // Building an immutable graph
  ImmutableGraph<String> immutableGraph =
      GraphBuilder.undirected()
          .allowsSelfLoops(true)
          .<String>immutable()
          .putEdge("bread", "bread")
          .putEdge("chocolate", "peanut butter")
          .putEdge("peanut butter", "jelly")
          .build(); 
 
@endcode
 @author James Sexton
 @author Joshua O'Madadhain
 @since 20.0
 */
@interface ComGoogleCommonGraphGraphBuilder : ComGoogleCommonGraphAbstractGraphBuilder

#pragma mark Public

/*!
 @brief Specifies whether the graph will allow self-loops (edges that connect a node to itself).
 Attempting to add a self-loop to a graph that does not allow them will throw an <code>UnsupportedOperationException</code>
 .
  
 <p>The default value is <code>false</code>.
 */
- (ComGoogleCommonGraphGraphBuilder *)allowsSelfLoopsWithBoolean:(jboolean)allowsSelfLoops;

/*!
 @brief Returns an empty <code>MutableGraph</code> with the properties of this <code>GraphBuilder</code>.
 */
- (id<ComGoogleCommonGraphMutableGraph>)build;

/*!
 @brief Returns a <code>GraphBuilder</code> for building directed graphs.
 */
+ (ComGoogleCommonGraphGraphBuilder *)directed;

/*!
 @brief Specifies the expected number of nodes in the graph.
 @throw IllegalArgumentExceptionif <code>expectedNodeCount</code> is negative
 */
- (ComGoogleCommonGraphGraphBuilder *)expectedNodeCountWithInt:(jint)expectedNodeCount;

/*!
 @brief Returns a <code>GraphBuilder</code> initialized with all properties queryable from <code>graph</code>.
 <p>The "queryable" properties are those that are exposed through the <code>Graph</code> interface,
  such as <code>Graph.isDirected()</code>. Other properties, such as <code>expectedNodeCount(int)</code>,
  are not set in the new builder.
 */
+ (ComGoogleCommonGraphGraphBuilder *)fromWithComGoogleCommonGraphGraph:(id<ComGoogleCommonGraphGraph> __nonnull)graph;

/*!
 @brief Returns an <code>ImmutableGraph.Builder</code> with the properties of this <code>GraphBuilder</code>.
 <p>The returned builder can be used for populating an <code>ImmutableGraph</code>.
  
 <p>Note that the returned builder will always have <code>incidentEdgeOrder</code> set to <code>ElementOrder.stable()</code>
 , regardless of the value that was set in this builder.
 @since 28.0
 */
- (ComGoogleCommonGraphImmutableGraph_Builder *)immutable;

/*!
 @brief Specifies the order of iteration for the elements of <code>Graph.edges()</code>, <code>Graph.adjacentNodes(Object)</code>
 , <code>Graph.predecessors(Object)</code>, <code>Graph.successors(Object)</code>
  and <code>Graph.incidentEdges(Object)</code>.
 <p>The default value is <code>unordered</code> for mutable graphs. For
  immutable graphs, this value is ignored; they always have a <code>stable</code>
  order.
 @throw IllegalArgumentExceptionif <code>incidentEdgeOrder</code> is not either <code>ElementOrder.unordered()</code>
  or <code>ElementOrder.stable()</code>.
 @since 29.0
 */
- (ComGoogleCommonGraphGraphBuilder *)incidentEdgeOrderWithComGoogleCommonGraphElementOrder:(ComGoogleCommonGraphElementOrder * __nonnull)incidentEdgeOrder;

/*!
 @brief Specifies the order of iteration for the elements of <code>Graph.nodes()</code>.
 <p>The default value is <code>insertion order</code>.
 */
- (ComGoogleCommonGraphGraphBuilder *)nodeOrderWithComGoogleCommonGraphElementOrder:(ComGoogleCommonGraphElementOrder * __nonnull)nodeOrder;

/*!
 @brief Returns a <code>GraphBuilder</code> for building undirected graphs.
 */
+ (ComGoogleCommonGraphGraphBuilder *)undirected;

#pragma mark Package-Private

- (ComGoogleCommonGraphGraphBuilder *)copy__ OBJC_METHOD_FAMILY_NONE;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initPackagePrivateWithBoolean:(jboolean)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonGraphGraphBuilder)

FOUNDATION_EXPORT ComGoogleCommonGraphGraphBuilder *ComGoogleCommonGraphGraphBuilder_directed(void);

FOUNDATION_EXPORT ComGoogleCommonGraphGraphBuilder *ComGoogleCommonGraphGraphBuilder_undirected(void);

FOUNDATION_EXPORT ComGoogleCommonGraphGraphBuilder *ComGoogleCommonGraphGraphBuilder_fromWithComGoogleCommonGraphGraph_(id<ComGoogleCommonGraphGraph> graph);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonGraphGraphBuilder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonGraphGraphBuilder")
