//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/build_result/java/com/google/common/graph/IncidentEdgeSet.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonGraphIncidentEdgeSet")
#ifdef RESTRICT_ComGoogleCommonGraphIncidentEdgeSet
#define INCLUDE_ALL_ComGoogleCommonGraphIncidentEdgeSet 0
#else
#define INCLUDE_ALL_ComGoogleCommonGraphIncidentEdgeSet 1
#endif
#undef RESTRICT_ComGoogleCommonGraphIncidentEdgeSet

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonGraphIncidentEdgeSet_) && (INCLUDE_ALL_ComGoogleCommonGraphIncidentEdgeSet || defined(INCLUDE_ComGoogleCommonGraphIncidentEdgeSet))
#define ComGoogleCommonGraphIncidentEdgeSet_

#define RESTRICT_JavaUtilAbstractSet 1
#define INCLUDE_JavaUtilAbstractSet 1
#include "java/util/AbstractSet.h"

@protocol ComGoogleCommonGraphBaseGraph;

/*!
 @brief Abstract base class for an incident edges set that allows different implementations of <code>AbstractSet.iterator()</code>
 .
 */
@interface ComGoogleCommonGraphIncidentEdgeSet : JavaUtilAbstractSet {
 @public
  id node_;
  id<ComGoogleCommonGraphBaseGraph> graph_;
}

#pragma mark Public

- (jboolean)containsWithId:(id __nullable)obj;

- (jboolean)removeWithId:(id __nonnull)o;

- (jint)size;

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivateWithComGoogleCommonGraphBaseGraph:(id<ComGoogleCommonGraphBaseGraph> __nonnull)graph
                                                                       withId:(id __nonnull)node;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonGraphIncidentEdgeSet)

J2OBJC_FIELD_SETTER(ComGoogleCommonGraphIncidentEdgeSet, node_, id)
J2OBJC_FIELD_SETTER(ComGoogleCommonGraphIncidentEdgeSet, graph_, id<ComGoogleCommonGraphBaseGraph>)

FOUNDATION_EXPORT void ComGoogleCommonGraphIncidentEdgeSet_initPackagePrivateWithComGoogleCommonGraphBaseGraph_withId_(ComGoogleCommonGraphIncidentEdgeSet *self, id<ComGoogleCommonGraphBaseGraph> graph, id node);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonGraphIncidentEdgeSet)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonGraphIncidentEdgeSet")
