//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/build_result/java/com/google/common/graph/StandardMutableNetwork.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonGraphStandardMutableNetwork")
#ifdef RESTRICT_ComGoogleCommonGraphStandardMutableNetwork
#define INCLUDE_ALL_ComGoogleCommonGraphStandardMutableNetwork 0
#else
#define INCLUDE_ALL_ComGoogleCommonGraphStandardMutableNetwork 1
#endif
#undef RESTRICT_ComGoogleCommonGraphStandardMutableNetwork

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonGraphStandardMutableNetwork_) && (INCLUDE_ALL_ComGoogleCommonGraphStandardMutableNetwork || defined(INCLUDE_ComGoogleCommonGraphStandardMutableNetwork))
#define ComGoogleCommonGraphStandardMutableNetwork_

#define RESTRICT_ComGoogleCommonGraphStandardNetwork 1
#define INCLUDE_ComGoogleCommonGraphStandardNetwork 1
#include "com/google/common/graph/StandardNetwork.h"

#define RESTRICT_ComGoogleCommonGraphMutableNetwork 1
#define INCLUDE_ComGoogleCommonGraphMutableNetwork 1
#include "com/google/common/graph/MutableNetwork.h"

@class ComGoogleCommonGraphEndpointPair;
@class ComGoogleCommonGraphNetworkBuilder;
@protocol JavaUtilMap;

/*!
 @brief Standard implementation of <code>MutableNetwork</code> that supports both directed and undirected
  graphs.Instances of this class should be constructed with <code>NetworkBuilder</code>.
 <p>Time complexities for mutation methods are all O(1) except for <code>removeNode(N node)</code>,
  which is in O(d_node) where d_node is the degree of <code>node</code>.
 @author James Sexton
 @author Joshua O'Madadhain
 @author Omar Darwish
 */
@interface ComGoogleCommonGraphStandardMutableNetwork : ComGoogleCommonGraphStandardNetwork < ComGoogleCommonGraphMutableNetwork >

#pragma mark Public

- (jboolean)addEdgeWithComGoogleCommonGraphEndpointPair:(ComGoogleCommonGraphEndpointPair * __nonnull)endpoints
                                                 withId:(id __nonnull)edge;

- (jboolean)addEdgeWithId:(id __nonnull)nodeU
                   withId:(id __nonnull)nodeV
                   withId:(id __nonnull)edge;

- (jboolean)addNodeWithId:(id __nonnull)node;

- (jboolean)removeEdgeWithId:(id __nonnull)edge;

- (jboolean)removeNodeWithId:(id __nonnull)node;

#pragma mark Package-Private

/*!
 @brief Constructs a mutable graph with the properties specified in <code>builder</code>.
 */
- (instancetype __nonnull)initPackagePrivateWithComGoogleCommonGraphNetworkBuilder:(ComGoogleCommonGraphNetworkBuilder * __nonnull)builder;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initPackagePrivateWithComGoogleCommonGraphNetworkBuilder:(ComGoogleCommonGraphNetworkBuilder * __nonnull)arg0
                                                                   withJavaUtilMap:(id<JavaUtilMap> __nonnull)arg1
                                                                   withJavaUtilMap:(id<JavaUtilMap> __nonnull)arg2 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonGraphStandardMutableNetwork)

FOUNDATION_EXPORT void ComGoogleCommonGraphStandardMutableNetwork_initPackagePrivateWithComGoogleCommonGraphNetworkBuilder_(ComGoogleCommonGraphStandardMutableNetwork *self, ComGoogleCommonGraphNetworkBuilder *builder);

FOUNDATION_EXPORT ComGoogleCommonGraphStandardMutableNetwork *new_ComGoogleCommonGraphStandardMutableNetwork_initPackagePrivateWithComGoogleCommonGraphNetworkBuilder_(ComGoogleCommonGraphNetworkBuilder *builder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonGraphStandardMutableNetwork *create_ComGoogleCommonGraphStandardMutableNetwork_initPackagePrivateWithComGoogleCommonGraphNetworkBuilder_(ComGoogleCommonGraphNetworkBuilder *builder);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonGraphStandardMutableNetwork)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonGraphStandardMutableNetwork")
