//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/runner/FilterFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnerFilterFactory")
#ifdef RESTRICT_OrgJunitRunnerFilterFactory
#define INCLUDE_ALL_OrgJunitRunnerFilterFactory 0
#else
#define INCLUDE_ALL_OrgJunitRunnerFilterFactory 1
#endif
#undef RESTRICT_OrgJunitRunnerFilterFactory

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitRunnerFilterFactory_) && (INCLUDE_ALL_OrgJunitRunnerFilterFactory || defined(INCLUDE_OrgJunitRunnerFilterFactory))
#define OrgJunitRunnerFilterFactory_

@class OrgJunitRunnerFilterFactoryParams;
@class OrgJunitRunnerManipulationFilter;

/*!
 @brief Extend this class to create a factory that creates <code>Filter</code>.
 */
@protocol OrgJunitRunnerFilterFactory < JavaObject >

/*!
 @brief Creates a <code>Filter</code> given a <code>FilterFactoryParams</code> argument.
 @param params Parameters needed to create the <code>Filter</code>
 */
- (OrgJunitRunnerManipulationFilter *)createFilterWithOrgJunitRunnerFilterFactoryParams:(OrgJunitRunnerFilterFactoryParams *)params;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnerFilterFactory)

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnerFilterFactory)

#endif

#if !defined (OrgJunitRunnerFilterFactory_FilterNotCreatedException_) && (INCLUDE_ALL_OrgJunitRunnerFilterFactory || defined(INCLUDE_OrgJunitRunnerFilterFactory_FilterNotCreatedException))
#define OrgJunitRunnerFilterFactory_FilterNotCreatedException_

#define RESTRICT_JavaLangException 1
#define INCLUDE_JavaLangException 1
#include "java/lang/Exception.h"

@class JavaLangThrowable;

/*!
 @brief Exception thrown if the <code>Filter</code> cannot be created.
 */
@interface OrgJunitRunnerFilterFactory_FilterNotCreatedException : JavaLangException

#pragma mark Public

- (instancetype __nonnull)initWithJavaLangException:(JavaLangException *)exception;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

- (instancetype __nonnull)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1
                               withBoolean:(jboolean)arg2
                               withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnerFilterFactory_FilterNotCreatedException)

FOUNDATION_EXPORT void OrgJunitRunnerFilterFactory_FilterNotCreatedException_initWithJavaLangException_(OrgJunitRunnerFilterFactory_FilterNotCreatedException *self, JavaLangException *exception);

FOUNDATION_EXPORT OrgJunitRunnerFilterFactory_FilterNotCreatedException *new_OrgJunitRunnerFilterFactory_FilterNotCreatedException_initWithJavaLangException_(JavaLangException *exception) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitRunnerFilterFactory_FilterNotCreatedException *create_OrgJunitRunnerFilterFactory_FilterNotCreatedException_initWithJavaLangException_(JavaLangException *exception);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnerFilterFactory_FilterNotCreatedException)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnerFilterFactory")
