//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/build_result/java/com/google/common/net/MediaType.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonNetMediaType")
#ifdef RESTRICT_ComGoogleCommonNetMediaType
#define INCLUDE_ALL_ComGoogleCommonNetMediaType 0
#else
#define INCLUDE_ALL_ComGoogleCommonNetMediaType 1
#endif
#undef RESTRICT_ComGoogleCommonNetMediaType

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonNetMediaType_) && (INCLUDE_ALL_ComGoogleCommonNetMediaType || defined(INCLUDE_ComGoogleCommonNetMediaType))
#define ComGoogleCommonNetMediaType_

@class ComGoogleCommonBaseOptional;
@class ComGoogleCommonCollectImmutableListMultimap;
@class JavaNioCharsetCharset;
@protocol ComGoogleCommonCollectMultimap;
@protocol JavaLangIterable;

/*!
 @brief Represents an <a href="http://en.wikipedia.org/wiki/Internet_media_type">Internet Media Type</a>
  (also known as a MIME Type or Content Type).This class also supports the concept of media ranges 
 <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1">defined by HTTP/1.1</a>.
 As such, the <code>*</code> character is treated as a wildcard and is used to represent any acceptable
  type or subtype value. A media type may not have wildcard type with a declared subtype. The 
 <code>*</code> character has no special meaning as part of a parameter. All values for type, subtype,
  parameter attributes or parameter values must be valid according to RFCs <a href="https://tools.ietf.org/html/rfc2045">
 2045</a> and <a href="https://tools.ietf.org/html/rfc2046">
 2046</a>.
  
 <p>All portions of the media type that are case-insensitive (type, subtype, parameter attributes)
  are normalized to lowercase. The value of the <code>charset</code> parameter is normalized to
  lowercase, but all others are left as-is. 
 <p>Note that this specifically does <strong>not</strong> represent the value of the MIME <code>Content-Type</code>
  header and as such has no support for header-specific considerations such as line
  folding and comments. 
 <p>For media types that take a charset the predefined constants default to UTF-8 and have a
  "_UTF_8" suffix. To get a version without a character set, use <code>withoutParameters</code>.
 @since 12.0
 @author Gregory Kick
 */
@interface ComGoogleCommonNetMediaType : NSObject
@property (readonly, class, strong) ComGoogleCommonNetMediaType *ANY_TYPE NS_SWIFT_NAME(ANY_TYPE);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *ANY_TEXT_TYPE NS_SWIFT_NAME(ANY_TEXT_TYPE);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *ANY_IMAGE_TYPE NS_SWIFT_NAME(ANY_IMAGE_TYPE);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *ANY_AUDIO_TYPE NS_SWIFT_NAME(ANY_AUDIO_TYPE);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *ANY_VIDEO_TYPE NS_SWIFT_NAME(ANY_VIDEO_TYPE);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *ANY_APPLICATION_TYPE NS_SWIFT_NAME(ANY_APPLICATION_TYPE);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *ANY_FONT_TYPE NS_SWIFT_NAME(ANY_FONT_TYPE);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *CACHE_MANIFEST_UTF_8 NS_SWIFT_NAME(CACHE_MANIFEST_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *CSS_UTF_8 NS_SWIFT_NAME(CSS_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *CSV_UTF_8 NS_SWIFT_NAME(CSV_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *HTML_UTF_8 NS_SWIFT_NAME(HTML_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *I_CALENDAR_UTF_8 NS_SWIFT_NAME(I_CALENDAR_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *PLAIN_TEXT_UTF_8 NS_SWIFT_NAME(PLAIN_TEXT_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *TEXT_JAVASCRIPT_UTF_8 NS_SWIFT_NAME(TEXT_JAVASCRIPT_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *TSV_UTF_8 NS_SWIFT_NAME(TSV_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *VCARD_UTF_8 NS_SWIFT_NAME(VCARD_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *WML_UTF_8 NS_SWIFT_NAME(WML_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *XML_UTF_8 NS_SWIFT_NAME(XML_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *VTT_UTF_8 NS_SWIFT_NAME(VTT_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *BMP NS_SWIFT_NAME(BMP);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *CRW NS_SWIFT_NAME(CRW);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *GIF NS_SWIFT_NAME(GIF);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *ICO NS_SWIFT_NAME(ICO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *JPEG NS_SWIFT_NAME(JPEG);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *PNG NS_SWIFT_NAME(PNG);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *PSD NS_SWIFT_NAME(PSD);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *SVG_UTF_8 NS_SWIFT_NAME(SVG_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *TIFF NS_SWIFT_NAME(TIFF);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *WEBP NS_SWIFT_NAME(WEBP);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *HEIF NS_SWIFT_NAME(HEIF);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *JP2K NS_SWIFT_NAME(JP2K);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MP4_AUDIO NS_SWIFT_NAME(MP4_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MPEG_AUDIO NS_SWIFT_NAME(MPEG_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OGG_AUDIO NS_SWIFT_NAME(OGG_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *WEBM_AUDIO NS_SWIFT_NAME(WEBM_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *L16_AUDIO NS_SWIFT_NAME(L16_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *L24_AUDIO NS_SWIFT_NAME(L24_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *BASIC_AUDIO NS_SWIFT_NAME(BASIC_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *AAC_AUDIO NS_SWIFT_NAME(AAC_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *VORBIS_AUDIO NS_SWIFT_NAME(VORBIS_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *WMA_AUDIO NS_SWIFT_NAME(WMA_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *WAX_AUDIO NS_SWIFT_NAME(WAX_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *VND_REAL_AUDIO NS_SWIFT_NAME(VND_REAL_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *VND_WAVE_AUDIO NS_SWIFT_NAME(VND_WAVE_AUDIO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MP4_VIDEO NS_SWIFT_NAME(MP4_VIDEO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MPEG_VIDEO NS_SWIFT_NAME(MPEG_VIDEO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OGG_VIDEO NS_SWIFT_NAME(OGG_VIDEO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *QUICKTIME NS_SWIFT_NAME(QUICKTIME);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *WEBM_VIDEO NS_SWIFT_NAME(WEBM_VIDEO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *WMV NS_SWIFT_NAME(WMV);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *FLV_VIDEO NS_SWIFT_NAME(FLV_VIDEO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *THREE_GPP_VIDEO NS_SWIFT_NAME(THREE_GPP_VIDEO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *THREE_GPP2_VIDEO NS_SWIFT_NAME(THREE_GPP2_VIDEO);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *APPLICATION_XML_UTF_8 NS_SWIFT_NAME(APPLICATION_XML_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *ATOM_UTF_8 NS_SWIFT_NAME(ATOM_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *BZIP2 NS_SWIFT_NAME(BZIP2);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *DART_UTF_8 NS_SWIFT_NAME(DART_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *APPLE_PASSBOOK NS_SWIFT_NAME(APPLE_PASSBOOK);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *EOT NS_SWIFT_NAME(EOT);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *EPUB NS_SWIFT_NAME(EPUB);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *FORM_DATA NS_SWIFT_NAME(FORM_DATA);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *KEY_ARCHIVE NS_SWIFT_NAME(KEY_ARCHIVE);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *APPLICATION_BINARY NS_SWIFT_NAME(APPLICATION_BINARY);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *GEO_JSON NS_SWIFT_NAME(GEO_JSON);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *GZIP NS_SWIFT_NAME(GZIP);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *HAL_JSON NS_SWIFT_NAME(HAL_JSON);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *JAVASCRIPT_UTF_8 NS_SWIFT_NAME(JAVASCRIPT_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *JOSE NS_SWIFT_NAME(JOSE);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *JOSE_JSON NS_SWIFT_NAME(JOSE_JSON);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *JSON_UTF_8 NS_SWIFT_NAME(JSON_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MANIFEST_JSON_UTF_8 NS_SWIFT_NAME(MANIFEST_JSON_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *KML NS_SWIFT_NAME(KML);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *KMZ NS_SWIFT_NAME(KMZ);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MBOX NS_SWIFT_NAME(MBOX);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *APPLE_MOBILE_CONFIG NS_SWIFT_NAME(APPLE_MOBILE_CONFIG);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MICROSOFT_EXCEL NS_SWIFT_NAME(MICROSOFT_EXCEL);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MICROSOFT_OUTLOOK NS_SWIFT_NAME(MICROSOFT_OUTLOOK);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MICROSOFT_POWERPOINT NS_SWIFT_NAME(MICROSOFT_POWERPOINT);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MICROSOFT_WORD NS_SWIFT_NAME(MICROSOFT_WORD);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *MEDIA_PRESENTATION_DESCRIPTION NS_SWIFT_NAME(MEDIA_PRESENTATION_DESCRIPTION);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *WASM_APPLICATION NS_SWIFT_NAME(WASM_APPLICATION);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *NACL_APPLICATION NS_SWIFT_NAME(NACL_APPLICATION);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *NACL_PORTABLE_APPLICATION NS_SWIFT_NAME(NACL_PORTABLE_APPLICATION);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OCTET_STREAM NS_SWIFT_NAME(OCTET_STREAM);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OGG_CONTAINER NS_SWIFT_NAME(OGG_CONTAINER);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OOXML_DOCUMENT NS_SWIFT_NAME(OOXML_DOCUMENT);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OOXML_PRESENTATION NS_SWIFT_NAME(OOXML_PRESENTATION);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OOXML_SHEET NS_SWIFT_NAME(OOXML_SHEET);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OPENDOCUMENT_GRAPHICS NS_SWIFT_NAME(OPENDOCUMENT_GRAPHICS);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OPENDOCUMENT_PRESENTATION NS_SWIFT_NAME(OPENDOCUMENT_PRESENTATION);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OPENDOCUMENT_SPREADSHEET NS_SWIFT_NAME(OPENDOCUMENT_SPREADSHEET);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OPENDOCUMENT_TEXT NS_SWIFT_NAME(OPENDOCUMENT_TEXT);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *OPENSEARCH_DESCRIPTION_UTF_8 NS_SWIFT_NAME(OPENSEARCH_DESCRIPTION_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *PDF NS_SWIFT_NAME(PDF);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *POSTSCRIPT NS_SWIFT_NAME(POSTSCRIPT);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *PROTOBUF NS_SWIFT_NAME(PROTOBUF);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *RDF_XML_UTF_8 NS_SWIFT_NAME(RDF_XML_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *RTF_UTF_8 NS_SWIFT_NAME(RTF_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *SFNT NS_SWIFT_NAME(SFNT);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *SHOCKWAVE_FLASH NS_SWIFT_NAME(SHOCKWAVE_FLASH);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *SKETCHUP NS_SWIFT_NAME(SKETCHUP);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *SOAP_XML_UTF_8 NS_SWIFT_NAME(SOAP_XML_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *TAR NS_SWIFT_NAME(TAR);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *WOFF NS_SWIFT_NAME(WOFF);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *WOFF2 NS_SWIFT_NAME(WOFF2);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *XHTML_UTF_8 NS_SWIFT_NAME(XHTML_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *XRD_UTF_8 NS_SWIFT_NAME(XRD_UTF_8);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *ZIP NS_SWIFT_NAME(ZIP);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *FONT_COLLECTION NS_SWIFT_NAME(FONT_COLLECTION);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *FONT_OTF NS_SWIFT_NAME(FONT_OTF);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *FONT_SFNT NS_SWIFT_NAME(FONT_SFNT);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *FONT_TTF NS_SWIFT_NAME(FONT_TTF);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *FONT_WOFF NS_SWIFT_NAME(FONT_WOFF);
@property (readonly, class, strong) ComGoogleCommonNetMediaType *FONT_WOFF2 NS_SWIFT_NAME(FONT_WOFF2);

#pragma mark Public

/*!
 @brief Returns an optional charset for the value of the charset parameter if it is specified.
 @throw IllegalStateExceptionif multiple charset values have been set for this media type
 @throw IllegalCharsetNameExceptionif a charset value is present, but illegal
 @throw UnsupportedCharsetExceptionif a charset value is present, but no support is available
      in this instance of the Java virtual machine
 */
- (ComGoogleCommonBaseOptional *)charset;

/*!
 @brief Creates a new media type with the given type and subtype.
 @throw IllegalArgumentExceptionif type or subtype is invalid or if a wildcard is used for the
      type, but not the subtype.
 */
+ (ComGoogleCommonNetMediaType *)createWithNSString:(NSString * __nonnull)type
                                       withNSString:(NSString * __nonnull)subtype;

- (jboolean)isEqual:(id __nullable)obj;

- (NSUInteger)hash;

/*!
 @brief Returns true if either the type or subtype is the wildcard.
 */
- (jboolean)hasWildcard;

/*!
 @brief Returns <code>true</code> if this instance falls within the range (as defined by <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html">
 the HTTP Accept header</a>) given
  by the argument according to three criteria: 
 <ol>
    <li>The type of the argument is the wildcard or equal to the type of this instance.
 <li>The subtype of the argument is the wildcard or equal to the subtype of this instance.
    <li>All of the parameters present in the argument are present in this instance. 
 </ol>
  
 <p>For example: 
 @code
 PLAIN_TEXT_UTF_8.is(PLAIN_TEXT_UTF_8) // true
  PLAIN_TEXT_UTF_8.is(HTML_UTF_8) // false
  PLAIN_TEXT_UTF_8.is(ANY_TYPE) // true
  PLAIN_TEXT_UTF_8.is(ANY_TEXT_TYPE) // true
  PLAIN_TEXT_UTF_8.is(ANY_IMAGE_TYPE) // false
  PLAIN_TEXT_UTF_8.is(ANY_TEXT_TYPE.withCharset(UTF_8)) // true
  PLAIN_TEXT_UTF_8.withoutParameters().is(ANY_TEXT_TYPE.withCharset(UTF_8)) // false
  PLAIN_TEXT_UTF_8.is(ANY_TEXT_TYPE.withCharset(UTF_16)) // false 
 
@endcode
  
 <p>Note that while it is possible to have the same parameter declared multiple times within a
  media type this method does not consider the number of occurrences of a parameter. For example, 
 <code>"text/plain; charset=UTF-8"</code> satisfies <code>"text/plain; charset=UTF-8;
  charset=UTF-8"</code>
 .
 */
- (jboolean)isWithComGoogleCommonNetMediaType:(ComGoogleCommonNetMediaType * __nonnull)mediaTypeRange;

/*!
 @brief Returns a multimap containing the parameters of this media type.
 */
- (ComGoogleCommonCollectImmutableListMultimap *)parameters;

/*!
 @brief Parses a media type from its string representation.
 @throw IllegalArgumentExceptionif the input is not parsable
 */
+ (ComGoogleCommonNetMediaType *)parseWithNSString:(NSString * __nonnull)input;

/*!
 @brief Returns the media subtype.For example, <code>"plain"</code> in <code>"text/plain"</code>.
 */
- (NSString *)subtype;

/*!
 @brief Returns the string representation of this media type in the format described in <a href="http://www.ietf.org/rfc/rfc2045.txt">
 RFC 2045</a>.
 */
- (NSString *)description;

/*!
 @brief Returns the top-level media type.For example, <code>"text"</code> in <code>"text/plain"</code>.
 */
- (NSString *)type;

/*!
 @brief Returns a new instance with the same type and subtype as this instance, with the <code>charset</code>
  parameter set to the <code>name</code> of the given charset.Only one <code>charset</code>
  parameter will be present on the new instance regardless of the number set on this
  one.
 <p>If a charset must be specified that is not supported on this JVM (and thus is not
  representable as a <code>Charset</code> instance, use <code>withParameter</code>.
 */
- (ComGoogleCommonNetMediaType *)withCharsetWithJavaNioCharsetCharset:(JavaNioCharsetCharset * __nonnull)charset;

/*!
 @brief Returns a new instance with the same type and subtype as this instance, but without any
  parameters.
 */
- (ComGoogleCommonNetMediaType *)withoutParameters;

/*!
 @brief <em>Replaces</em> all parameters with the given attribute with a single parameter with the
  given value.If multiple parameters with the same attributes are necessary use <code>withParameters(String, Iterable)</code>
 .
 Prefer <code>withCharset</code> for setting the <code>charset</code>
  parameter when using a <code>Charset</code> object.
 @throw IllegalArgumentExceptionif either <code>attribute</code> or <code>value</code> is invalid
 */
- (ComGoogleCommonNetMediaType *)withParameterWithNSString:(NSString * __nonnull)attribute
                                              withNSString:(NSString * __nonnull)value;

/*!
 @brief <em>Replaces</em> all parameters with the given parameters.
 @throw IllegalArgumentExceptionif any parameter or value is invalid
 */
- (ComGoogleCommonNetMediaType *)withParametersWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap> __nonnull)parameters;

/*!
 @brief <em>Replaces</em> all parameters with the given attribute with parameters using the given
  values.If there are no values, any existing parameters with the given attribute are removed.
 @throw IllegalArgumentExceptionif either <code>attribute</code> or <code>values</code> is invalid
 @since 24.0
 */
- (ComGoogleCommonNetMediaType *)withParametersWithNSString:(NSString * __nonnull)attribute
                                       withJavaLangIterable:(id<JavaLangIterable> __nonnull)values;

#pragma mark Package-Private

/*!
 @brief Creates a media type with the "application" type and the given subtype.
 @throw IllegalArgumentExceptionif subtype is invalid
 */
+ (ComGoogleCommonNetMediaType *)createApplicationTypeWithNSString:(NSString * __nonnull)subtype;

/*!
 @brief Creates a media type with the "audio" type and the given subtype.
 @throw IllegalArgumentExceptionif subtype is invalid
 */
+ (ComGoogleCommonNetMediaType *)createAudioTypeWithNSString:(NSString * __nonnull)subtype;

/*!
 @brief Creates a media type with the "font" type and the given subtype.
 @throw IllegalArgumentExceptionif subtype is invalid
 */
+ (ComGoogleCommonNetMediaType *)createFontTypeWithNSString:(NSString * __nonnull)subtype;

/*!
 @brief Creates a media type with the "image" type and the given subtype.
 @throw IllegalArgumentExceptionif subtype is invalid
 */
+ (ComGoogleCommonNetMediaType *)createImageTypeWithNSString:(NSString * __nonnull)subtype;

/*!
 @brief Creates a media type with the "text" type and the given subtype.
 @throw IllegalArgumentExceptionif subtype is invalid
 */
+ (ComGoogleCommonNetMediaType *)createTextTypeWithNSString:(NSString * __nonnull)subtype;

/*!
 @brief Creates a media type with the "video" type and the given subtype.
 @throw IllegalArgumentExceptionif subtype is invalid
 */
+ (ComGoogleCommonNetMediaType *)createVideoTypeWithNSString:(NSString * __nonnull)subtype;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonNetMediaType)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_ANY_TYPE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_ANY_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, ANY_TYPE, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_ANY_TEXT_TYPE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_ANY_TEXT_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, ANY_TEXT_TYPE, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_ANY_IMAGE_TYPE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_ANY_IMAGE_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, ANY_IMAGE_TYPE, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_ANY_AUDIO_TYPE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_ANY_AUDIO_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, ANY_AUDIO_TYPE, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_ANY_VIDEO_TYPE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_ANY_VIDEO_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, ANY_VIDEO_TYPE, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_ANY_APPLICATION_TYPE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_ANY_APPLICATION_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, ANY_APPLICATION_TYPE, ComGoogleCommonNetMediaType *)

/*!
 @brief Wildcard matching any "font" top-level media type.
 @since 30.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_ANY_FONT_TYPE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_ANY_FONT_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, ANY_FONT_TYPE, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_CACHE_MANIFEST_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_CACHE_MANIFEST_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, CACHE_MANIFEST_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_CSS_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_CSS_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, CSS_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_CSV_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_CSV_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, CSV_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_HTML_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_HTML_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, HTML_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_I_CALENDAR_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_I_CALENDAR_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, I_CALENDAR_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_PLAIN_TEXT_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_PLAIN_TEXT_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, PLAIN_TEXT_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://www.rfc-editor.org/rfc/rfc4329.txt">RFC 4329</a> declares <code>application/javascript</code>
  to be the correct media type for JavaScript, but this
  may be necessary in certain situations for compatibility.
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_TEXT_JAVASCRIPT_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_TEXT_JAVASCRIPT_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, TEXT_JAVASCRIPT_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://www.iana.org/assignments/media-types/text/tab-separated-values">Tab separated
  values</a>.
 @since 15.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_TSV_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_TSV_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, TSV_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_VCARD_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_VCARD_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, VCARD_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief UTF-8 encoded <a href="https://en.wikipedia.org/wiki/Wireless_Markup_Language">Wireless Markup
  Language</a>.
 @since 13.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_WML_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_WML_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, WML_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief As described in <a href="http://www.ietf.org/rfc/rfc3023.txt">RFC 3023</a>, this constant
  (<code>text/xml</code>) is used for XML documents that are "readable by casual users."
 <code>APPLICATION_XML_UTF_8</code>
  is provided for documents that are intended for applications.
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_XML_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_XML_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, XML_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief As described in <a href="https://w3c.github.io/webvtt/#iana-text-vtt">the VTT spec</a>, this is
  used for Web Video Text Tracks (WebVTT) files, used with the HTML5 track element.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_VTT_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_VTT_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, VTT_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://en.wikipedia.org/wiki/BMP_file_format">Bitmap file format</a> (<code>bmp</code>
  files).
 @since 13.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_BMP(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_BMP;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, BMP, ComGoogleCommonNetMediaType *)

/*!
 @brief The <a href="https://en.wikipedia.org/wiki/Camera_Image_File_Format">Canon Image File
  Format</a> (<code>crw</code> files), a widely-used "raw image" format for cameras.It is found in 
 <code>/etc/mime.types</code>, e.g. in <a href="http://anonscm.debian.org/gitweb/?
 p=collab-maint/mime-support.git;a=blob;f=mime.types;hb=HEAD">
 Debian 3.48-1</a>.
 @since 15.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_CRW(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_CRW;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, CRW, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_GIF(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_GIF;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, GIF, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_ICO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_ICO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, ICO, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_JPEG(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_JPEG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, JPEG, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_PNG(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_PNG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, PNG, ComGoogleCommonNetMediaType *)

/*!
 @brief The Photoshop File Format (<code>psd</code> files) as defined by <a href="http://www.iana.org/assignments/media-types/image/vnd.adobe.photoshop">
 IANA</a>, and
  found in <code>/etc/mime.types</code>, e.g.
 <a href="http://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x/conf/mime.types">
 </a> of the
  Apache <a href="http://httpd.apache.org/">HTTPD project</a>; for the specification, see <a href="http://www.adobe.com/devnet-apps/photoshop/fileformatashtml/PhotoshopFileFormats.htm">
  Adobe Photoshop Document Format</a> and <a href="http://en.wikipedia.org/wiki/Adobe_Photoshop#File_format">
 Wikipedia</a>; this is the
  regular output/input of Photoshop (which can also export to various image formats; note that
  files with extension "PSB" are in a distinct but related format). 
 <p>This is a more recent replacement for the older, experimental type <code>x-photoshop</code>: <a href="http://tools.ietf.org/html/rfc2046#section-6">
 RFC-2046.6</a>.
 @since 15.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_PSD(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_PSD;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, PSD, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_SVG_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_SVG_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, SVG_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_TIFF(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_TIFF;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, TIFF, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://en.wikipedia.org/wiki/WebP">WebP image format</a>.
 @since 13.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_WEBP(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_WEBP;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, WEBP, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://www.iana.org/assignments/media-types/image/heif">HEIF image format</a>.
 @since 28.1
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_HEIF(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_HEIF;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, HEIF, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://tools.ietf.org/html/rfc3745">JP2K image format</a>.
 @since 28.1
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_JP2K(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_JP2K;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, JP2K, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MP4_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MP4_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MP4_AUDIO, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MPEG_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MPEG_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MPEG_AUDIO, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OGG_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OGG_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OGG_AUDIO, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_WEBM_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_WEBM_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, WEBM_AUDIO, ComGoogleCommonNetMediaType *)

/*!
 @brief L16 audio, as defined by <a href="https://tools.ietf.org/html/rfc2586">RFC 2586</a>.
 @since 24.1
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_L16_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_L16_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, L16_AUDIO, ComGoogleCommonNetMediaType *)

/*!
 @brief L24 audio, as defined by <a href="https://tools.ietf.org/html/rfc3190">RFC 3190</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_L24_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_L24_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, L24_AUDIO, ComGoogleCommonNetMediaType *)

/*!
 @brief Basic Audio, as defined by <a href="http://tools.ietf.org/html/rfc2046#section-4.3">RFC
  2046</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_BASIC_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_BASIC_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, BASIC_AUDIO, ComGoogleCommonNetMediaType *)

/*!
 @brief Advanced Audio Coding.For more information, see <a href="https://en.wikipedia.org/wiki/Advanced_Audio_Coding">
 Advanced Audio Coding</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_AAC_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_AAC_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, AAC_AUDIO, ComGoogleCommonNetMediaType *)

/*!
 @brief Vorbis Audio, as defined by <a href="http://tools.ietf.org/html/rfc5215">RFC 5215</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_VORBIS_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_VORBIS_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, VORBIS_AUDIO, ComGoogleCommonNetMediaType *)

/*!
 @brief Windows Media Audio.For more information, see <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/dd562994(v=vs.85).aspx">
 file
  name extensions for Windows Media metafiles</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_WMA_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_WMA_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, WMA_AUDIO, ComGoogleCommonNetMediaType *)

/*!
 @brief Windows Media metafiles.For more information, see <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/dd562994(v=vs.85).aspx">
 file
  name extensions for Windows Media metafiles</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_WAX_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_WAX_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, WAX_AUDIO, ComGoogleCommonNetMediaType *)

/*!
 @brief Real Audio.For more information, see <a href="http://service.real.com/help/faq/rp8/configrp8win.html">
 this link</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_VND_REAL_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_VND_REAL_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, VND_REAL_AUDIO, ComGoogleCommonNetMediaType *)

/*!
 @brief WAVE format, as defined by <a href="https://tools.ietf.org/html/rfc2361">RFC 2361</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_VND_WAVE_AUDIO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_VND_WAVE_AUDIO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, VND_WAVE_AUDIO, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MP4_VIDEO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MP4_VIDEO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MP4_VIDEO, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MPEG_VIDEO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MPEG_VIDEO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MPEG_VIDEO, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OGG_VIDEO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OGG_VIDEO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OGG_VIDEO, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_QUICKTIME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_QUICKTIME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, QUICKTIME, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_WEBM_VIDEO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_WEBM_VIDEO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, WEBM_VIDEO, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_WMV(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_WMV;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, WMV, ComGoogleCommonNetMediaType *)

/*!
 @brief Flash video.For more information, see <a href="http://help.adobe.com/en_US/ActionScript/3.0_ProgrammingAS3/WS5b3ccc516d4fbf351e63e3d118a9b90204-7d48.html">
 this link</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_FLV_VIDEO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_FLV_VIDEO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, FLV_VIDEO, ComGoogleCommonNetMediaType *)

/*!
 @brief The 3GP multimedia container format.For more information, see <a href="ftp://www.3gpp.org/tsg_sa/TSG_SA/TSGS_23/Docs/PDF/SP-040065.pdf#page=10">
 3GPP TS
  26.244</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_THREE_GPP_VIDEO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_THREE_GPP_VIDEO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, THREE_GPP_VIDEO, ComGoogleCommonNetMediaType *)

/*!
 @brief The 3G2 multimedia container format.For more information, see <a href="http://www.3gpp2.org/Public_html/specs/C.S0050-B_v1.0_070521.pdf#page=16">
 3GPP2
  C.S0050-B</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_THREE_GPP2_VIDEO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_THREE_GPP2_VIDEO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, THREE_GPP2_VIDEO, ComGoogleCommonNetMediaType *)

/*!
 @brief As described in <a href="http://www.ietf.org/rfc/rfc3023.txt">RFC 3023</a>, this constant
  (<code>application/xml</code>) is used for XML documents that are "unreadable by casual users."
 <code>XML_UTF_8</code> is provided for documents that may be read by users.
 @since 14.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_APPLICATION_XML_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_APPLICATION_XML_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, APPLICATION_XML_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_ATOM_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_ATOM_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, ATOM_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_BZIP2(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_BZIP2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, BZIP2, ComGoogleCommonNetMediaType *)

/*!
 @brief Files in the <a href="https://www.dartlang.org/articles/embedding-in-html/">dart</a>
  programming language.
 @since 19.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_DART_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_DART_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, DART_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://goo.gl/2QoMvg">Apple Passbook</a>.
 @since 19.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_APPLE_PASSBOOK(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_APPLE_PASSBOOK;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, APPLE_PASSBOOK, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://en.wikipedia.org/wiki/Embedded_OpenType">Embedded OpenType</a> fonts.This is 
 <a href="http://www.iana.org/assignments/media-types/application/vnd.ms-fontobject">registered
  </a> with the IANA.
 @since 17.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_EOT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_EOT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, EOT, ComGoogleCommonNetMediaType *)

/*!
 @brief As described in the <a href="http://idpf.org/epub">International Digital Publishing Forum</a>
  EPUB is the distribution and interchange format standard for digital publications and
  documents.This media type is defined in the <a href="http://www.idpf.org/epub/30/spec/epub30-ocf.html">
 EPUB Open Container Format</a>
  specification.
 @since 15.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_EPUB(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_EPUB;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, EPUB, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_FORM_DATA(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_FORM_DATA;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, FORM_DATA, ComGoogleCommonNetMediaType *)

/*!
 @brief As described in <a href="https://www.rsa.com/rsalabs/node.asp?
 id=2138">PKCS #12: Personal
  Information Exchange Syntax Standard</a>, PKCS #12 defines an archive file format for storing
  many cryptography objects as a single file.
 @since 15.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_KEY_ARCHIVE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_KEY_ARCHIVE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, KEY_ARCHIVE, ComGoogleCommonNetMediaType *)

/*!
 @brief This is a non-standard media type, but is commonly used in serving hosted binary files as it is 
 <a href="http://code.google.com/p/browsersec/wiki/Part2#Survey_of_content_sniffing_behaviors">
  known not to trigger content sniffing in current browsers</a>.It <i>should not</i> be used in
  other situations as it is not specified by any RFC and does not appear in the <a href="http://www.iana.org/assignments/media-types">
 /IANA MIME Media Types</a> list.
 Consider 
 <code>OCTET_STREAM</code> for binary data that is not being served to a browser.
 @since 14.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_APPLICATION_BINARY(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_APPLICATION_BINARY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, APPLICATION_BINARY, ComGoogleCommonNetMediaType *)

/*!
 @brief Media type for the <a href="https://tools.ietf.org/html/rfc7946">GeoJSON Format</a>, a
  geospatial data interchange format based on JSON.
 @since 28.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_GEO_JSON(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_GEO_JSON;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, GEO_JSON, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_GZIP(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_GZIP;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, GZIP, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://tools.ietf.org/html/draft-kelly-json-hal-08#section-3">JSON Hypertext
  Application Language (HAL) documents</a>.
 @since 26.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_HAL_JSON(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_HAL_JSON;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, HAL_JSON, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://www.rfc-editor.org/rfc/rfc4329.txt">RFC 4329</a> declares this to be the
  correct media type for JavaScript, but <code>text/javascript</code> may be
  necessary in certain situations for compatibility.
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_JAVASCRIPT_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_JAVASCRIPT_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, JAVASCRIPT_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief For <a href="https://tools.ietf.org/html/rfc7515">JWS or JWE objects using the Compact
  Serialization</a>.
 @since 27.1
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_JOSE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_JOSE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, JOSE, ComGoogleCommonNetMediaType *)

/*!
 @brief For <a href="https://tools.ietf.org/html/rfc7515">JWS or JWE objects using the JSON
  Serialization</a>.
 @since 27.1
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_JOSE_JSON(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_JOSE_JSON;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, JOSE_JSON, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_JSON_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_JSON_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, JSON_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief The <a href="http://www.w3.org/TR/appmanifest/">Manifest for a web application</a>.
 @since 19.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MANIFEST_JSON_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MANIFEST_JSON_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MANIFEST_JSON_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://www.opengeospatial.org/standards/kml/">OGC KML (Keyhole Markup Language)</a>.
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_KML(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_KML;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, KML, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://www.opengeospatial.org/standards/kml/">OGC KML (Keyhole Markup Language)</a>,
  compressed using the ZIP format into KMZ archives.
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_KMZ(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_KMZ;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, KMZ, ComGoogleCommonNetMediaType *)

/*!
 @brief The <a href="https://tools.ietf.org/html/rfc4155">mbox database format</a>.
 @since 13.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MBOX(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MBOX;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MBOX, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://goo.gl/1pGBFm">Apple over-the-air mobile configuration profiles</a>.
 @since 18.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_APPLE_MOBILE_CONFIG(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_APPLE_MOBILE_CONFIG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, APPLE_MOBILE_CONFIG, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://goo.gl/XDQ1h2">Microsoft Excel</a> spreadsheets.
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MICROSOFT_EXCEL(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MICROSOFT_EXCEL;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MICROSOFT_EXCEL, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://goo.gl/XrTEqG">Microsoft Outlook</a> items.
 @since 27.1
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MICROSOFT_OUTLOOK(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MICROSOFT_OUTLOOK;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MICROSOFT_OUTLOOK, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://goo.gl/XDQ1h2">Microsoft Powerpoint</a> presentations.
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MICROSOFT_POWERPOINT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MICROSOFT_POWERPOINT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MICROSOFT_POWERPOINT, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://goo.gl/XDQ1h2">Microsoft Word</a> documents.
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MICROSOFT_WORD(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MICROSOFT_WORD;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MICROSOFT_WORD, ComGoogleCommonNetMediaType *)

/*!
 @brief Media type for <a href="https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP">
 Dynamic Adaptive
  Streaming over HTTP (DASH)</a>.This is <a href="https://www.iana.org/assignments/media-types/application/dash+xml">
 registered</a> with
  the IANA.
 @since 28.2
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_MEDIA_PRESENTATION_DESCRIPTION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_MEDIA_PRESENTATION_DESCRIPTION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, MEDIA_PRESENTATION_DESCRIPTION, ComGoogleCommonNetMediaType *)

/*!
 @brief WASM applications.For more information see <a href="https://webassembly.org/">the Web Assembly
  overview</a>.
 @since 27.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_WASM_APPLICATION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_WASM_APPLICATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, WASM_APPLICATION, ComGoogleCommonNetMediaType *)

/*!
 @brief NaCl applications.For more information see <a href="https://developer.chrome.com/native-client/devguide/coding/application-structure">
 the
  Developer Guide for Native Client Application Structure</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_NACL_APPLICATION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_NACL_APPLICATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, NACL_APPLICATION, ComGoogleCommonNetMediaType *)

/*!
 @brief NaCl portable applications.For more information see <a href="https://developer.chrome.com/native-client/devguide/coding/application-structure">
 the
  Developer Guide for Native Client Application Structure</a>.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_NACL_PORTABLE_APPLICATION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_NACL_PORTABLE_APPLICATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, NACL_PORTABLE_APPLICATION, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OCTET_STREAM(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OCTET_STREAM;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OCTET_STREAM, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OGG_CONTAINER(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OGG_CONTAINER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OGG_CONTAINER, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OOXML_DOCUMENT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OOXML_DOCUMENT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OOXML_DOCUMENT, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OOXML_PRESENTATION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OOXML_PRESENTATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OOXML_PRESENTATION, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OOXML_SHEET(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OOXML_SHEET;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OOXML_SHEET, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OPENDOCUMENT_GRAPHICS(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OPENDOCUMENT_GRAPHICS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OPENDOCUMENT_GRAPHICS, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OPENDOCUMENT_PRESENTATION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OPENDOCUMENT_PRESENTATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OPENDOCUMENT_PRESENTATION, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OPENDOCUMENT_SPREADSHEET(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OPENDOCUMENT_SPREADSHEET;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OPENDOCUMENT_SPREADSHEET, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OPENDOCUMENT_TEXT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OPENDOCUMENT_TEXT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OPENDOCUMENT_TEXT, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://tools.ietf.org/id/draft-ellermann-opensearch-01.html">OpenSearch</a>
  Description files are XML files that describe how a website can be used as a search engine by
  consumers (e.g.web browsers).
 @since 28.2
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_OPENSEARCH_DESCRIPTION_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_OPENSEARCH_DESCRIPTION_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, OPENSEARCH_DESCRIPTION_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_PDF(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_PDF;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, PDF, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_POSTSCRIPT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_POSTSCRIPT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, POSTSCRIPT, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://tools.ietf.org/html/draft-rfernando-protocol-buffers-00">Protocol buffers</a>
 @since 15.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_PROTOBUF(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_PROTOBUF;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, PROTOBUF, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://en.wikipedia.org/wiki/RDF/XML">RDF/XML</a> documents, which are XML
  serializations of <a href="https://en.wikipedia.org/wiki/Resource_Description_Framework">
 Resource Description
  Framework</a> graphs.
 @since 14.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_RDF_XML_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_RDF_XML_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, RDF_XML_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_RTF_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_RTF_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, RTF_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://tools.ietf.org/html/rfc8081">RFC 8081</a> declares <code>font/sfnt</code>
  to be the correct media type for SFNT, but this may be necessary in certain
  situations for compatibility.
 @since 17.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_SFNT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_SFNT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, SFNT, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_SHOCKWAVE_FLASH(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_SHOCKWAVE_FLASH;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, SHOCKWAVE_FLASH, ComGoogleCommonNetMediaType *)

/*!
 @brief <code>skp</code> files produced by the 3D Modeling software <a href="https://www.sketchup.com/">
 SketchUp</a>
 @since 13.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_SKETCHUP(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_SKETCHUP;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, SKETCHUP, ComGoogleCommonNetMediaType *)

/*!
 @brief As described in <a href="http://www.ietf.org/rfc/rfc3902.txt">RFC 3902</a>, this constant
  (<code>application/soap+xml</code>) is used to identify SOAP 1.2 message envelopes that have been
  serialized with XML 1.0.
 <p>For SOAP 1.1 messages, see <code>XML_UTF_8</code> per <a href="http://www.w3.org/TR/2000/NOTE-SOAP-20000508/">
 W3C Note on Simple Object Access Protocol
  (SOAP) 1.1</a>
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_SOAP_XML_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_SOAP_XML_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, SOAP_XML_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_TAR(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_TAR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, TAR, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://tools.ietf.org/html/rfc8081">RFC 8081</a> declares <code>font/woff</code>
  to be the correct media type for WOFF, but this may be necessary in certain
  situations for compatibility.
 @since 17.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_WOFF(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_WOFF;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, WOFF, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://tools.ietf.org/html/rfc8081">RFC 8081</a> declares <code>font/woff2</code>
  to be the correct media type for WOFF2, but this may be necessary in certain
  situations for compatibility.
 @since 20.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_WOFF2(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_WOFF2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, WOFF2, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_XHTML_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_XHTML_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, XHTML_UTF_8, ComGoogleCommonNetMediaType *)

/*!
 @brief Extensible Resource Descriptors.This is not yet registered with the IANA, but it is specified
  by OASIS in the <a href="http://docs.oasis-open.org/xri/xrd/v1.0/cd02/xrd-1.0-cd02.html">XRD
  definition</a> and implemented in projects such as <a href="http://code.google.com/p/webfinger/">
 WebFinger</a>.
 @since 14.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_XRD_UTF_8(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_XRD_UTF_8;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, XRD_UTF_8, ComGoogleCommonNetMediaType *)

inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_ZIP(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_ZIP;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, ZIP, ComGoogleCommonNetMediaType *)

/*!
 @brief A collection of font outlines as defined by <a href="https://tools.ietf.org/html/rfc8081">RFC
  8081</a>.
 @since 30.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_FONT_COLLECTION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_FONT_COLLECTION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, FONT_COLLECTION, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://en.wikipedia.org/wiki/OpenType">Open Type Font Format</a> (OTF) as defined by 
 <a href="https://tools.ietf.org/html/rfc8081">RFC 8081</a>.
 @since 30.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_FONT_OTF(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_FONT_OTF;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, FONT_OTF, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://en.wikipedia.org/wiki/SFNT">Spline or Scalable Font Format</a> (SFNT).
 <a href="https://tools.ietf.org/html/rfc8081">
 RFC 8081</a> declares this to be the correct media
  type for SFNT, but <code>application/font-sfnt</code> may be necessary in certain situations
  for compatibility.
 @since 30.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_FONT_SFNT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_FONT_SFNT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, FONT_SFNT, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="https://en.wikipedia.org/wiki/TrueType">True Type Font Format</a> (TTF) as defined by 
 <a href="https://tools.ietf.org/html/rfc8081">RFC 8081</a>.
 @since 30.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_FONT_TTF(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_FONT_TTF;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, FONT_TTF, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://en.wikipedia.org/wiki/Web_Open_Font_Format">Web Open Font Format</a> (WOFF).
 <a href="https://tools.ietf.org/html/rfc8081">
 RFC 8081</a> declares this to be the correct media
  type for SFNT, but <code>application/font-woff</code> may be necessary in certain situations
  for compatibility.
 @since 30.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_FONT_WOFF(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_FONT_WOFF;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, FONT_WOFF, ComGoogleCommonNetMediaType *)

/*!
 @brief <a href="http://en.wikipedia.org/wiki/Web_Open_Font_Format">Web Open Font Format</a> (WOFF2).
 <a href="https://tools.ietf.org/html/rfc8081">RFC 8081</a> declares this to be the correct
  media type for SFNT, but <code>application/font-woff2</code> may be necessary in certain
  situations for compatibility.
 @since 30.0
 */
inline ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_get_FONT_WOFF2(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_FONT_WOFF2;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonNetMediaType, FONT_WOFF2, ComGoogleCommonNetMediaType *)

FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_createWithNSString_withNSString_(NSString *type, NSString *subtype);

FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_createApplicationTypeWithNSString_(NSString *subtype);

FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_createAudioTypeWithNSString_(NSString *subtype);

FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_createFontTypeWithNSString_(NSString *subtype);

FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_createImageTypeWithNSString_(NSString *subtype);

FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_createTextTypeWithNSString_(NSString *subtype);

FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_createVideoTypeWithNSString_(NSString *subtype);

FOUNDATION_EXPORT ComGoogleCommonNetMediaType *ComGoogleCommonNetMediaType_parseWithNSString_(NSString *input);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonNetMediaType)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonNetMediaType")
