//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/runner/manipulation/Orderable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnerManipulationOrderable")
#ifdef RESTRICT_OrgJunitRunnerManipulationOrderable
#define INCLUDE_ALL_OrgJunitRunnerManipulationOrderable 0
#else
#define INCLUDE_ALL_OrgJunitRunnerManipulationOrderable 1
#endif
#undef RESTRICT_OrgJunitRunnerManipulationOrderable

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitRunnerManipulationOrderable_) && (INCLUDE_ALL_OrgJunitRunnerManipulationOrderable || defined(INCLUDE_OrgJunitRunnerManipulationOrderable))
#define OrgJunitRunnerManipulationOrderable_

#define RESTRICT_OrgJunitRunnerManipulationSortable 1
#define INCLUDE_OrgJunitRunnerManipulationSortable 1
#include "org/junit/runner/manipulation/Sortable.h"

@class OrgJunitRunnerManipulationOrderer;

/*!
 @brief Interface for runners that allow ordering of tests.
 <p>Beware of using this interface to cope with order dependencies between tests.
  Tests that are isolated from each other are less expensive to maintain and
  can be run individually.
 @since 4.13
 */
@protocol OrgJunitRunnerManipulationOrderable < OrgJunitRunnerManipulationSortable, JavaObject >

/*!
 @brief Orders the tests using <code>orderer</code>
 @throw InvalidOrderingExceptionif orderer does something invalid (like remove or add
  children)
 */
- (void)orderWithOrgJunitRunnerManipulationOrderer:(OrgJunitRunnerManipulationOrderer *)orderer;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnerManipulationOrderable)

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnerManipulationOrderable)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnerManipulationOrderable")
