//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/internal/runners/rules/RuleMemberValidator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitInternalRunnersRulesRuleMemberValidator")
#ifdef RESTRICT_OrgJunitInternalRunnersRulesRuleMemberValidator
#define INCLUDE_ALL_OrgJunitInternalRunnersRulesRuleMemberValidator 0
#else
#define INCLUDE_ALL_OrgJunitInternalRunnersRulesRuleMemberValidator 1
#endif
#undef RESTRICT_OrgJunitInternalRunnersRulesRuleMemberValidator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitInternalRunnersRulesRuleMemberValidator_) && (INCLUDE_ALL_OrgJunitInternalRunnersRulesRuleMemberValidator || defined(INCLUDE_OrgJunitInternalRunnersRulesRuleMemberValidator))
#define OrgJunitInternalRunnersRulesRuleMemberValidator_

@class OrgJunitInternalRunnersRulesRuleMemberValidator_Builder;
@class OrgJunitRunnersModelTestClass;
@protocol JavaUtilList;

/*!
 @brief A RuleMemberValidator validates the rule fields/methods of a 
 <code>org.junit.runners.model.TestClass</code>.All reasons for rejecting the 
 <code>TestClass</code> are written to a list of errors.
 <p>There are four slightly different validators. The <code>CLASS_RULE_VALIDATOR</code>
  validates fields with a <code>ClassRule</code> annotation and the 
 <code>RULE_VALIDATOR</code> validates fields with a <code>Rule</code> annotation.</p>
  
 <p>The <code>CLASS_RULE_METHOD_VALIDATOR</code>
  validates methods with a <code>ClassRule</code> annotation and the 
 <code>RULE_METHOD_VALIDATOR</code> validates methods with a <code>Rule</code> annotation.</p>
 */
@interface OrgJunitInternalRunnersRulesRuleMemberValidator : NSObject
@property (readonly, class, strong) OrgJunitInternalRunnersRulesRuleMemberValidator *CLASS_RULE_VALIDATOR NS_SWIFT_NAME(CLASS_RULE_VALIDATOR);
@property (readonly, class, strong) OrgJunitInternalRunnersRulesRuleMemberValidator *RULE_VALIDATOR NS_SWIFT_NAME(RULE_VALIDATOR);
@property (readonly, class, strong) OrgJunitInternalRunnersRulesRuleMemberValidator *CLASS_RULE_METHOD_VALIDATOR NS_SWIFT_NAME(CLASS_RULE_METHOD_VALIDATOR);
@property (readonly, class, strong) OrgJunitInternalRunnersRulesRuleMemberValidator *RULE_METHOD_VALIDATOR NS_SWIFT_NAME(RULE_METHOD_VALIDATOR);

#pragma mark Public

/*!
 @brief Validate the <code>org.junit.runners.model.TestClass</code> and adds reasons
  for rejecting the class to a list of errors.
 @param target the <code>TestClass</code>  to validate.
 @param errors the list of errors.
 */
- (void)validateWithOrgJunitRunnersModelTestClass:(OrgJunitRunnersModelTestClass *)target
                                 withJavaUtilList:(id<JavaUtilList>)errors;

#pragma mark Package-Private

- (instancetype __nonnull)initWithOrgJunitInternalRunnersRulesRuleMemberValidator_Builder:(OrgJunitInternalRunnersRulesRuleMemberValidator_Builder *)builder;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(OrgJunitInternalRunnersRulesRuleMemberValidator)

/*!
 @brief Validates fields with a <code>ClassRule</code> annotation.
 */
inline OrgJunitInternalRunnersRulesRuleMemberValidator *OrgJunitInternalRunnersRulesRuleMemberValidator_get_CLASS_RULE_VALIDATOR(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgJunitInternalRunnersRulesRuleMemberValidator *OrgJunitInternalRunnersRulesRuleMemberValidator_CLASS_RULE_VALIDATOR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJunitInternalRunnersRulesRuleMemberValidator, CLASS_RULE_VALIDATOR, OrgJunitInternalRunnersRulesRuleMemberValidator *)

/*!
 @brief Validates fields with a <code>Rule</code> annotation.
 */
inline OrgJunitInternalRunnersRulesRuleMemberValidator *OrgJunitInternalRunnersRulesRuleMemberValidator_get_RULE_VALIDATOR(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgJunitInternalRunnersRulesRuleMemberValidator *OrgJunitInternalRunnersRulesRuleMemberValidator_RULE_VALIDATOR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJunitInternalRunnersRulesRuleMemberValidator, RULE_VALIDATOR, OrgJunitInternalRunnersRulesRuleMemberValidator *)

/*!
 @brief Validates methods with a <code>ClassRule</code> annotation.
 */
inline OrgJunitInternalRunnersRulesRuleMemberValidator *OrgJunitInternalRunnersRulesRuleMemberValidator_get_CLASS_RULE_METHOD_VALIDATOR(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgJunitInternalRunnersRulesRuleMemberValidator *OrgJunitInternalRunnersRulesRuleMemberValidator_CLASS_RULE_METHOD_VALIDATOR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJunitInternalRunnersRulesRuleMemberValidator, CLASS_RULE_METHOD_VALIDATOR, OrgJunitInternalRunnersRulesRuleMemberValidator *)

/*!
 @brief Validates methods with a <code>Rule</code> annotation.
 */
inline OrgJunitInternalRunnersRulesRuleMemberValidator *OrgJunitInternalRunnersRulesRuleMemberValidator_get_RULE_METHOD_VALIDATOR(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgJunitInternalRunnersRulesRuleMemberValidator *OrgJunitInternalRunnersRulesRuleMemberValidator_RULE_METHOD_VALIDATOR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJunitInternalRunnersRulesRuleMemberValidator, RULE_METHOD_VALIDATOR, OrgJunitInternalRunnersRulesRuleMemberValidator *)

FOUNDATION_EXPORT void OrgJunitInternalRunnersRulesRuleMemberValidator_initWithOrgJunitInternalRunnersRulesRuleMemberValidator_Builder_(OrgJunitInternalRunnersRulesRuleMemberValidator *self, OrgJunitInternalRunnersRulesRuleMemberValidator_Builder *builder);

FOUNDATION_EXPORT OrgJunitInternalRunnersRulesRuleMemberValidator *new_OrgJunitInternalRunnersRulesRuleMemberValidator_initWithOrgJunitInternalRunnersRulesRuleMemberValidator_Builder_(OrgJunitInternalRunnersRulesRuleMemberValidator_Builder *builder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitInternalRunnersRulesRuleMemberValidator *create_OrgJunitInternalRunnersRulesRuleMemberValidator_initWithOrgJunitInternalRunnersRulesRuleMemberValidator_Builder_(OrgJunitInternalRunnersRulesRuleMemberValidator_Builder *builder);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalRunnersRulesRuleMemberValidator)

#endif

#if !defined (OrgJunitInternalRunnersRulesRuleMemberValidator_RuleValidator_) && (INCLUDE_ALL_OrgJunitInternalRunnersRulesRuleMemberValidator || defined(INCLUDE_OrgJunitInternalRunnersRulesRuleMemberValidator_RuleValidator))
#define OrgJunitInternalRunnersRulesRuleMemberValidator_RuleValidator_

@class IOSClass;
@class OrgJunitRunnersModelFrameworkMember;
@protocol JavaUtilList;

/*!
 @brief Encapsulates a single piece of validation logic, used to determine if <code>org.junit.Rule</code> and 
 <code>org.junit.ClassRule</code> annotations have been used correctly
 */
@protocol OrgJunitInternalRunnersRulesRuleMemberValidator_RuleValidator < JavaObject >

/*!
 @brief Examine the given member and add any violations of the strategy's validation logic to the given list of errors
 @param member The member (field or member) to examine
 @param annotation The type of rule annotation on the member
 @param errors The list of errors to add validation violations to
 */
- (void)validateWithOrgJunitRunnersModelFrameworkMember:(OrgJunitRunnersModelFrameworkMember *)member
                                           withIOSClass:(IOSClass *)annotation
                                       withJavaUtilList:(id<JavaUtilList>)errors;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitInternalRunnersRulesRuleMemberValidator_RuleValidator)

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalRunnersRulesRuleMemberValidator_RuleValidator)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitInternalRunnersRulesRuleMemberValidator")
