//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/experimental/categories/CategoryValidator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitExperimentalCategoriesCategoryValidator")
#ifdef RESTRICT_OrgJunitExperimentalCategoriesCategoryValidator
#define INCLUDE_ALL_OrgJunitExperimentalCategoriesCategoryValidator 0
#else
#define INCLUDE_ALL_OrgJunitExperimentalCategoriesCategoryValidator 1
#endif
#undef RESTRICT_OrgJunitExperimentalCategoriesCategoryValidator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitExperimentalCategoriesCategoryValidator_) && (INCLUDE_ALL_OrgJunitExperimentalCategoriesCategoryValidator || defined(INCLUDE_OrgJunitExperimentalCategoriesCategoryValidator))
#define OrgJunitExperimentalCategoriesCategoryValidator_

#define RESTRICT_OrgJunitValidatorAnnotationValidator 1
#define INCLUDE_OrgJunitValidatorAnnotationValidator 1
#include "org/junit/validator/AnnotationValidator.h"

@class OrgJunitRunnersModelFrameworkMethod;
@protocol JavaUtilList;

/*!
 @brief Validates that there are no errors in the use of the <code>Category</code>
  annotation.If there is, a <code>Throwable</code> object will be added to the list
  of errors.
 @since 4.12
 */
@interface OrgJunitExperimentalCategoriesCategoryValidator : OrgJunitValidatorAnnotationValidator

#pragma mark Public

- (instancetype __nonnull)init;

/*!
 @brief Adds to <code>errors</code> a throwable for each problem detected.Looks for 
 <code>BeforeClass</code>, <code>AfterClass</code>, <code>Before</code> and <code>After</code>
  annotations.
 @param method the method that is being validated
 @return A list of exceptions detected
 @since 4.12
 */
- (id<JavaUtilList>)validateAnnotatedMethodWithOrgJunitRunnersModelFrameworkMethod:(OrgJunitRunnersModelFrameworkMethod *)method;

@end

J2OBJC_STATIC_INIT(OrgJunitExperimentalCategoriesCategoryValidator)

FOUNDATION_EXPORT void OrgJunitExperimentalCategoriesCategoryValidator_init(OrgJunitExperimentalCategoriesCategoryValidator *self);

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategoryValidator *new_OrgJunitExperimentalCategoriesCategoryValidator_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategoryValidator *create_OrgJunitExperimentalCategoriesCategoryValidator_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitExperimentalCategoriesCategoryValidator)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitExperimentalCategoriesCategoryValidator")
