//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/experimental/categories/Categories.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitExperimentalCategoriesCategories")
#ifdef RESTRICT_OrgJunitExperimentalCategoriesCategories
#define INCLUDE_ALL_OrgJunitExperimentalCategoriesCategories 0
#else
#define INCLUDE_ALL_OrgJunitExperimentalCategoriesCategories 1
#endif
#undef RESTRICT_OrgJunitExperimentalCategoriesCategories

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgJunitExperimentalCategoriesCategories_) && (INCLUDE_ALL_OrgJunitExperimentalCategoriesCategories || defined(INCLUDE_OrgJunitExperimentalCategoriesCategories))
#define OrgJunitExperimentalCategoriesCategories_

#define RESTRICT_OrgJunitRunnersSuite 1
#define INCLUDE_OrgJunitRunnersSuite 1
#include "org/junit/runners/Suite.h"

@class IOSClass;
@class IOSObjectArray;
@class OrgJunitRunnersModelRunnerBuilder;
@protocol JavaUtilList;

/*!
 @brief From a given set of test classes, runs only the classes and methods that are
  annotated with either the category given with the @@IncludeCategory
  annotation, or a subtype of that category.
 <p>
  Note that, for now, annotating suites with <code>@@Category</code> has no effect.
  Categories must be annotated on the direct method or class. 
 <p>
  Example: 
 @code

  public interface FastTests {
  }
  public interface SlowTests {
  }
  public interface SmokeTests
  }
  public static class A {
          &#064;Test
      public void a() {
          fail();
      }     
     &#064;Category(SlowTests.class)
          &#064;Test
      public void b() {
      }     
     &#064;Category({FastTests.class, SmokeTests.class})
          &#064;Test
      public void c() {
      }    }    
  &#064;Category({SlowTests.class, FastTests.class})
  public static class B {
          &#064;Test
      public void d() {
      }    }    
  &#064;RunWith(Categories.class)
   &#064;IncludeCategory(SlowTests.class)
   &#064;SuiteClasses({A.class, B.class})
  // Note that Categories is a kind of Suite
  public static class SlowTestSuite {
      // Will run A.b and B.d, but not A.a and A.c
  } 
  
@endcode
  <p>
  Example to run multiple categories: 
 @code

   &#064;RunWith(Categories.class)
   &#064;IncludeCategory({FastTests.class, SmokeTests.class}) 
  &#064;SuiteClasses({A.class, B.class})
  public static class FastOrSmokeTestSuite {
      // Will run A.c and B.d, but not A.b because it is not any of FastTests or SmokeTests
  } 
  
@endcode
 @version 4.12
 - seealso: <a href="https://github.com/junit-team/junit4/wiki/Categories">Categories at JUnit wiki</a>
 */
@interface OrgJunitExperimentalCategoriesCategories : OrgJunitRunnersSuite

#pragma mark Public

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)klass
     withOrgJunitRunnersModelRunnerBuilder:(OrgJunitRunnersModelRunnerBuilder *)builder;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)arg0
                         withIOSClassArray:(IOSObjectArray *)arg1 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)arg0
                          withJavaUtilList:(id<JavaUtilList>)arg1 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithOrgJunitRunnersModelRunnerBuilder:(OrgJunitRunnersModelRunnerBuilder *)arg0
                                                       withIOSClass:(IOSClass *)arg1
                                                  withIOSClassArray:(IOSObjectArray *)arg2 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithOrgJunitRunnersModelRunnerBuilder:(OrgJunitRunnersModelRunnerBuilder *)arg0
                                                  withIOSClassArray:(IOSObjectArray *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitExperimentalCategoriesCategories)

FOUNDATION_EXPORT void OrgJunitExperimentalCategoriesCategories_initWithIOSClass_withOrgJunitRunnersModelRunnerBuilder_(OrgJunitExperimentalCategoriesCategories *self, IOSClass *klass, OrgJunitRunnersModelRunnerBuilder *builder);

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories *new_OrgJunitExperimentalCategoriesCategories_initWithIOSClass_withOrgJunitRunnersModelRunnerBuilder_(IOSClass *klass, OrgJunitRunnersModelRunnerBuilder *builder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories *create_OrgJunitExperimentalCategoriesCategories_initWithIOSClass_withOrgJunitRunnersModelRunnerBuilder_(IOSClass *klass, OrgJunitRunnersModelRunnerBuilder *builder);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitExperimentalCategoriesCategories)

#endif

#if !defined (OrgJunitExperimentalCategoriesCategories_IncludeCategory_) && (INCLUDE_ALL_OrgJunitExperimentalCategoriesCategories || defined(INCLUDE_OrgJunitExperimentalCategoriesCategories_IncludeCategory))
#define OrgJunitExperimentalCategoriesCategories_IncludeCategory_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class IOSObjectArray;

@protocol OrgJunitExperimentalCategoriesCategories_IncludeCategory < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;
@property (readonly) jboolean matchAny;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface OrgJunitExperimentalCategoriesCategories_IncludeCategory : NSObject < OrgJunitExperimentalCategoriesCategories_IncludeCategory > {
 @public
  IOSObjectArray *value_;
  jboolean matchAny_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitExperimentalCategoriesCategories_IncludeCategory)

FOUNDATION_EXPORT id<OrgJunitExperimentalCategoriesCategories_IncludeCategory> create_OrgJunitExperimentalCategoriesCategories_IncludeCategory(jboolean matchAny, IOSObjectArray *value);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitExperimentalCategoriesCategories_IncludeCategory)

#endif

#if !defined (OrgJunitExperimentalCategoriesCategories_ExcludeCategory_) && (INCLUDE_ALL_OrgJunitExperimentalCategoriesCategories || defined(INCLUDE_OrgJunitExperimentalCategoriesCategories_ExcludeCategory))
#define OrgJunitExperimentalCategoriesCategories_ExcludeCategory_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class IOSObjectArray;

@protocol OrgJunitExperimentalCategoriesCategories_ExcludeCategory < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;
@property (readonly) jboolean matchAny;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface OrgJunitExperimentalCategoriesCategories_ExcludeCategory : NSObject < OrgJunitExperimentalCategoriesCategories_ExcludeCategory > {
 @public
  IOSObjectArray *value_;
  jboolean matchAny_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitExperimentalCategoriesCategories_ExcludeCategory)

FOUNDATION_EXPORT id<OrgJunitExperimentalCategoriesCategories_ExcludeCategory> create_OrgJunitExperimentalCategoriesCategories_ExcludeCategory(jboolean matchAny, IOSObjectArray *value);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitExperimentalCategoriesCategories_ExcludeCategory)

#endif

#if !defined (OrgJunitExperimentalCategoriesCategories_CategoryFilter_) && (INCLUDE_ALL_OrgJunitExperimentalCategoriesCategories || defined(INCLUDE_OrgJunitExperimentalCategoriesCategories_CategoryFilter))
#define OrgJunitExperimentalCategoriesCategories_CategoryFilter_

#define RESTRICT_OrgJunitRunnerManipulationFilter 1
#define INCLUDE_OrgJunitRunnerManipulationFilter 1
#include "org/junit/runner/manipulation/Filter.h"

@class IOSClass;
@class IOSObjectArray;
@class OrgJunitRunnerDescription;
@protocol JavaUtilSet;

@interface OrgJunitExperimentalCategoriesCategories_CategoryFilter : OrgJunitRunnerManipulationFilter

#pragma mark Public

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)includedCategory
                              withIOSClass:(IOSClass *)excludedCategory __attribute__((deprecated));

+ (OrgJunitExperimentalCategoriesCategories_CategoryFilter *)categoryFilterWithBoolean:(jboolean)matchAnyInclusions
                                                                       withJavaUtilSet:(id<JavaUtilSet>)inclusions
                                                                           withBoolean:(jboolean)matchAnyExclusions
                                                                       withJavaUtilSet:(id<JavaUtilSet>)exclusions;

/*!
 - seealso: #toString()
 */
- (NSString *)describe;

+ (OrgJunitExperimentalCategoriesCategories_CategoryFilter *)excludeWithBoolean:(jboolean)matchAny
                                                              withIOSClassArray:(IOSObjectArray *)categories;

+ (OrgJunitExperimentalCategoriesCategories_CategoryFilter *)excludeWithIOSClass:(IOSClass *)category;

+ (OrgJunitExperimentalCategoriesCategories_CategoryFilter *)excludeWithIOSClassArray:(IOSObjectArray *)categories;

+ (OrgJunitExperimentalCategoriesCategories_CategoryFilter *)includeWithBoolean:(jboolean)matchAny
                                                              withIOSClassArray:(IOSObjectArray *)categories;

+ (OrgJunitExperimentalCategoriesCategories_CategoryFilter *)includeWithIOSClass:(IOSClass *)category;

+ (OrgJunitExperimentalCategoriesCategories_CategoryFilter *)includeWithIOSClassArray:(IOSObjectArray *)categories;

- (jboolean)shouldRunWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

/*!
 @brief Returns string in the form <tt>&quot;[included categories] - [excluded categories]&quot;</tt>, where both
  sets have comma separated names of categories.
 @return string representation for the relative complement of excluded categories set
  in the set of included categories. Examples: 
 <ul>
   <li> <tt>&quot;categories [all]&quot;</tt> for all included categories and no excluded ones;
   <li> <tt>&quot;categories [all] - [A, B]&quot;</tt> for all included categories and given excluded ones;
   <li> <tt>&quot;categories [A, B] - [C, D]&quot;</tt> for given included categories and given excluded ones. 
 </ul>
 - seealso: Class#toString()name of category
 */
- (NSString *)description;

#pragma mark Protected

- (instancetype __nonnull)initWithBoolean:(jboolean)matchAnyIncludes
                          withJavaUtilSet:(id<JavaUtilSet>)includes
                              withBoolean:(jboolean)matchAnyExcludes
                          withJavaUtilSet:(id<JavaUtilSet>)excludes;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitExperimentalCategoriesCategories_CategoryFilter)

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *OrgJunitExperimentalCategoriesCategories_CategoryFilter_includeWithBoolean_withIOSClassArray_(jboolean matchAny, IOSObjectArray *categories);

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *OrgJunitExperimentalCategoriesCategories_CategoryFilter_includeWithIOSClass_(IOSClass *category);

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *OrgJunitExperimentalCategoriesCategories_CategoryFilter_includeWithIOSClassArray_(IOSObjectArray *categories);

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *OrgJunitExperimentalCategoriesCategories_CategoryFilter_excludeWithBoolean_withIOSClassArray_(jboolean matchAny, IOSObjectArray *categories);

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *OrgJunitExperimentalCategoriesCategories_CategoryFilter_excludeWithIOSClass_(IOSClass *category);

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *OrgJunitExperimentalCategoriesCategories_CategoryFilter_excludeWithIOSClassArray_(IOSObjectArray *categories);

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *OrgJunitExperimentalCategoriesCategories_CategoryFilter_categoryFilterWithBoolean_withJavaUtilSet_withBoolean_withJavaUtilSet_(jboolean matchAnyInclusions, id<JavaUtilSet> inclusions, jboolean matchAnyExclusions, id<JavaUtilSet> exclusions);

FOUNDATION_EXPORT void OrgJunitExperimentalCategoriesCategories_CategoryFilter_initWithIOSClass_withIOSClass_(OrgJunitExperimentalCategoriesCategories_CategoryFilter *self, IOSClass *includedCategory, IOSClass *excludedCategory);

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *new_OrgJunitExperimentalCategoriesCategories_CategoryFilter_initWithIOSClass_withIOSClass_(IOSClass *includedCategory, IOSClass *excludedCategory) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *create_OrgJunitExperimentalCategoriesCategories_CategoryFilter_initWithIOSClass_withIOSClass_(IOSClass *includedCategory, IOSClass *excludedCategory);

FOUNDATION_EXPORT void OrgJunitExperimentalCategoriesCategories_CategoryFilter_initWithBoolean_withJavaUtilSet_withBoolean_withJavaUtilSet_(OrgJunitExperimentalCategoriesCategories_CategoryFilter *self, jboolean matchAnyIncludes, id<JavaUtilSet> includes, jboolean matchAnyExcludes, id<JavaUtilSet> excludes);

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *new_OrgJunitExperimentalCategoriesCategories_CategoryFilter_initWithBoolean_withJavaUtilSet_withBoolean_withJavaUtilSet_(jboolean matchAnyIncludes, id<JavaUtilSet> includes, jboolean matchAnyExcludes, id<JavaUtilSet> excludes) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitExperimentalCategoriesCategories_CategoryFilter *create_OrgJunitExperimentalCategoriesCategories_CategoryFilter_initWithBoolean_withJavaUtilSet_withBoolean_withJavaUtilSet_(jboolean matchAnyIncludes, id<JavaUtilSet> includes, jboolean matchAnyExcludes, id<JavaUtilSet> excludes);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitExperimentalCategoriesCategories_CategoryFilter)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitExperimentalCategoriesCategories")
